project:
  type: book
  execute-dir: project
  output-dir: docs
  
execute: 
  freeze: auto

format:
  html:
    theme:
      - lumen
    #grid: 
    #  sidebar-width: 250px
    fontsize: "100%"
    #template-partials:
    #  - toc.html
    toc-title: "On this page"
  pdf:
    documentclass: scrreprt
    mainfont: "Open Sans"
    fig-pos: "H"
    include-in-header:
      text: |
        \usepackage{float}
        \raggedbottom

book:
  title: "Central Virginia Planning District Regional Housing Study"
  repo-url: https://github.com/housingforwardva/cvpdc
  output-file: "cvpdc-housing-study"
  author: 
    name: "HousingForward Virginia"
    url: https://www.housingforwardva.org
  downloads: pdf 
  date: today
  date-format: long
  chapters:
    - index.qmd 
    - summary.qmd
    - part: "Research and engagement"
      chapters:
        - part-1-1.qmd # Background research
        - part-1-2.qmd # Engagement and outreach
    - part: "Findings"
      chapters: 
        - part-2-1.qmd # Regional market analysis
        - part-2-2.qmd # County market analyses
        - part-2-3.qmd # Lynchburg market analysis
    - part: "Policy evaluation"
      chapters:
        - part-3-1.qmd # Policy evaluation
    - part: "Policy recommendations"
      chapters: 
        - part-4-1.qmd # Regional solutions
        - part-4-2.qmd # Local partnerships
        - part-4-3.qmd # Amherst
        - part-4-4.qmd # Appomattox
        - part-4-5.qmd # Bedford
        - part-4-6.qmd # Campbell
        - part-4-7.qmd # Lynchburg
        - part-4-8.qmd # Towns
   # - part: "Appendix"

knitr:
  opts_chunk: 
    echo: false
    warning: false
    message: false
    
#comments: 
#  hypothesis: true
  

