project:
  type: book
  execute-dir: project
  output-dir: docs
  
execute: 
  freeze: auto

format:
  html:
    theme:
      - lumen
    grid: 
      sidebar-width: 350px
    fontsize: "100%"
    template-partials:
      - toc.html
    toc-title: "On this page"
  # pdf:
  #   documentclass: scrreprt
  #   mainfont: "Open Sans"
  #   fig-pos: "H"
  #   include-in-header:
  #     text: |
  #       \usepackage{float}
  #       \raggedbottom

book:
  title: "Central Virginia Planning District Regional Housing Market Analysis"
  repo-url: https://github.com/housingforwardva/cvpdc
  author: 
    name: "HousingForward Virginia"
    url: https://www.housingforwardva.org
  # downloads: pdf 
  date: today
  chapters:
    - index.qmd 
    - part: "PART 1: Introduction and background"
      chapters:
        - part-1-1.qmd # Introduction
        - part-1-2.qmd # Background research
    - part: "PART 2: Engagement summary"
      chapters:
        - part-2-1.qmd # Methods and themes
    - part: "PART 3: Findings"
      chapters: 
        - part-3-1.qmd # CVPDC Housing Market Assessment
        - part-3-2.qmd # County Housing Market Assessment
        - part-3-3.qmd # City of Lynchburg Housing Market Analysis
    - part: "PART 4: Policy evaluation"
      chapters:
        - part-4-1.qmd # Regional and local policy evaluation
    - part: "PART 5: Policy recommendations"
      chapters: 
        - part-5-1.qmd # Regional solutions
        - part-5-2.qmd # Local partnerships
        - part-5-3.qmd # Amherst
        - part-5-4.qmd # Appomattox
        - part-5-5.qmd # Bedford
        - part-5-6.qmd # Campbell
        - part-5-7.qmd # Lynchburg
        - part-5-8.qmd # Towns
   # - part: "Appendix"

knitr:
  opts_chunk: 
    echo: false
    warning: false
    message: false
    
comments: 
  hypothesis: true
  

