# Regional solutions {#part-4-1}

This group of solutions addresses issues common across the CVPDC region. They also require more advanced coordination between the PDC, all localities, and organizations that serve. These solutions, therefore, have the potential to impact the largest number of people in the region and can address shared issues through connected initiatives and campaigns.

## Primary solutions

### Create a regional housing education campaign

**Issue:** *Overcoming the stigma of affordable housing and building political will*

Public support for housing is a critical element for advancing policies that address land use barriers and increase investments in housing affordability. Many participants in local government meetings and focus groups shared specific examples for how misguided opposition has hindered progress in the region. Cross-sector education campaigns have been successful in other places to inform the public, elected officials, important regional institutions, and others about current challenges and potential strategies needed to achieve widespread enthusiasm for better housing across the region.

**Solution:** *Conduct a regional housing education campaign*

A cross-sector campaign uses strategic partnerships to advance a positive image of housing and demonstrate the importance of housing on the region's current and future success. A variety of methods can be tailored for different audiences and can include media interviews, op-eds and letters to the editor, fact sheets, and community meetings to build a shared housing narrative.

**FRAMEWORK**

This proposed campaign will use a range of methods to educate the public and other stakeholder groups about the region's housing needs, where and how gaps exist, and ways to overcome those challenges. The campaign can be divided into distinct efforts based on audience type:

-   **General public:** Create a "Housing 101" campaign to generate better understanding of the region's housing market, demographic trends, and policy mechanisms for the creation and preservation of quality, affordable housing. Methods include media interviews, op-eds and letters to the editor, fact sheets, and community meetings.

-   **Elected officials:** Local supervisors and councilpersons should receive targeted outreach that helps them understand the scope of housing needs in their communities, what efforts are currently underway, and what solutions their localities have at their disposal to overcome challenges. Efforts should also focus on the nexus between smart housing policy and economic development potential. Methods include direct meetings, data fact sheets, and policy white papers.

-   **Institutions:** Outreach to universities, hospitals, and large corporate employers should be conducted to gauge interest in public-private partnerships on affordable housing and financial support for a housing education campaign.

-   **Landlords:** Owners and managers of rental properties play a crucial role in expanding housing opportunity. Focus group participants mentioned concerns about the loss of small private landlords. Outreach should be conducted that educates landlords about the importance of accepting Housing Choice Vouchers.

-   **Housing builders and developers:** These businesses play an integral role in the creation and provision in the region; as such, there should be proactive outreach to 1) understand this industry's outlook on the market, 2) learn about any challenges encountered that negatively affect housing affordability, and 3) facilitate productive, solutions-oriented dialogue on ways this sector can advance housing opportunities.

**IMPLEMENTATION PLAN**

*Immediate (0-6 months):*

-   Explore formation of work group to oversee education campaign at a high level and ensure consistent messaging.

-   Gather contact information for primary stakeholders in each of the above categories.

-   Choose campaign ambassadors among work group members to lead outreach efforts for each audience type.

-   Outline major talking points needed for audience types.

*Short-term (6-12 months):*

-   Develop outreach plan by assigning contacts to designated liaisons with specific pitches and requests.

-   Create outreach materials as needed, including: fact sheets, social media posts, "layperson" policy briefs, presentation slides, and other relevant content. Investigate funding opportunities to sustain dedicated outreach efforts and potentially hire marketing consultant(s).

-   Plan, organize, and host a regional housing summit to gather all stakeholders. Focus themes on regional cooperation and collaborative solutions.

-   Evaluate progress to determine long-term goals of campaign(s); assess, reevaluate, and redesign outreach efforts as necessary to reflect changing housing needs in the region.

*Long-term (12-24 months):*

-   Consider a formal public opinion poll on attitudes toward housing development and affordability. The Campaign for Housing and Civic Engagement (CHACE) conducted a statewide poll in 2017 with the help of William & Mary, and should be used as a reference.

**RESPONSIBLE ACTORS AND THEIR ROLES**

-   CVPDC will kick-off this solution by beginning coordinated discussions with localities, nonprofit, and private sector partners. Other potential duties include oversight of work group and consultant(s).

-   HousingForward Virginia may assist CVPDC in the initial stages of campaign development and provide support through its Overcoming NIMBY and Inclusionary Housing initiatives (to be updated by end of 2023).

-   Local government staff will help CVPDC and its partners conduct outreach to important stakeholders, including elected officials.

**LEGAL, FINANCIAL, AND ORGANIZATIONAL CAPACITY**

-   There are no legal boundaries preventing these educational efforts.

-   Financial requirements are dependent on the scale of outreach actions. Sustained, professional-level marketing and public relations will likely require the use of paid consultants. It will also be important to secure access to electronic platforms and communication tools to disseminate information.

-   CVPDC and its member governments may be able to use existing public information officials for assistance.

**FUNDING SCOPE REQUIREMENTS**

-   The scope of funds required is contingent on the level of outreach desired. The lower end of this scale would take the shape of CVPDC staff, local government staff, and nonprofit/private partner staff incorporating these actions into their standard workload on a limited basis. The upper end would include new, dedicated funding to support new staff, contracted professionals, or both to support the work, particularly where capacity is currently stretched thin.

**POTENTIAL FUNDING SOURCES**

**Public sources:** Education campaigns for housing might be funded through collective operating dollars pooled by CVPDC and local governments. Funding may also be available via grant opportunities from Virginia Housing. Private sources: Philanthropic and corporate partners may also be interested in funding educational efforts. CVPDC should approach known funders who have an existing interest in housing and community development.

**METRICS TO EVALUATE SUCCESS**

**Campaign Reach:**

-   Number of people exposed to the campaign across all platforms.

-   Number of unique website visitors or landing page visits (if applicable).

-   Number of social media impressions and reach, split by platform.

**Audience Engagement:**

-   Number of social media interactions, including likes, shares, comments, and retweets.

-   Number of subscriptions or sign-ups for more information or follow-up resources.

-   Number of attendees at campaign-related events, webinars, or workshops.

**Behavior Change:**

-   Pre and post-campaign surveys to measure changes in knowledge, attitudes, or behaviors related to housing issues.

-   Number of inquiries or applications for housing assistance or other housing programs promoted during the campaign.

-   Changes in patterns of housing searches or inquiries, potentially tracked through partnerships with real estate platforms or local housing authorities.

**Economic Impact:**

-   Increases in investment or funding for affordable housing projects.

-   Increases in the number of affordable housing units built or planned.

-   Changes in housing policy that can be linked to increased awareness or advocacy related to the campaign.

**Feedback and Testimonials:**

-   Qualitative feedback collected through surveys, focus groups, or interviews.

-   Stories or testimonials from people who have been positively impacted by the campaign

**PROJECTED IMPACT**

-   Measuring the impact of education campaigns is not as simple as quantifying housing production or service delivery. Broad public support for housing is a necessary prerequisite for advancing policy solutions---and can only be achieved with higher levels of knowledge and saliency about the issue. If successful, such efforts will allow local policymakers, developers, and providers to more quickly, efficiently, and effectively expand housing opportunities.

::: callout-note

### Richmond Regional Housing Framework

**Approach:**

The Richmond Regional Housing Framework is a comprehensive strategy developed by the Partnership for Housing Affordability (PHA) with the aim to increase housing opportunity and affordability across the Richmond region in Virginia. It is designed to guide policy and investment decisions over the next 15 years, to enhance regional cooperation and public engagement, and provide more affordable housing options for all residents.

**Outcomes:**

In 2019, community engagement efforts, including survey responses, reached over **1,900 people** in the region. Priority housing challenges and common values were identified, and solutions are in progress (with some already completed). The framework's solution will serve as a roadmap to guide the region's housing efforts.

[Richmond Regional Housing Framework](https://pharva.com/framework/)

:::

### Maintain the PDC's role in regional housing goals

**Issue:** *Limited staff capacity among smaller counties and towns in the region can delay or prevent those communities from addressing their housing needs.*

Mid-size and smaller local governments in Virginia today face a range of housing challenges with limited abilities to effectively address them. Smaller budgets and fewer staff---particularly subject matter experts---often prevent these communities from generating and implementing successful policies.

**Solution**: *Establish new pathways for CVPDC to guide and support efforts to increase housing affordability throughout the region.*

Planning district commissions (PDCs) throughout Virginia have started or expanded collaborative efforts on housing affordability over the last several years. Notably, some of the more impressive examples are small-metro or non-metro regions outside of the Urban Crescent, which face many of the same conditions and challenges found in the Lynchburg area.

Expanded coordination and funding among local governments, fostered in large part by these PDCs, has helped accelerate meaningful solutions to address housing needs. CVPDC can lead similar efforts in this region with four successive steps:

1.  Coordinate ongoing housing conversations between the public, nonprofit, and private sectors,

2.  Use the findings and recommendations in this study to set specific action areas for PDC-led assistance,

3.  Seek and obtain sustainable funding sources to support dedicated housing positions within the PDC, and

4.  Begin exploring options to establish a regional revolving loan fund for affordable housing.

**FRAMEWORK**

**STEP 1:** *Keep the conversations going.*

Establish a regional housing task force made up of local officials, practitioners, and advocates who will continue regular conversations about housing needs and solutions. The PDC should be the preliminary convener and provide logistical support, such as arranging for virtual and in-person meeting venues.

This group should meet at least monthly for the first year following its creation. Meetings should also follow a semi-regular agenda to promote consistency and accountability.

Example of agenda for regional housing task force meeting:

-   Partner updates

-   Discussion of priority challenges

-   Discussion of new/ongoing solutions

-   Next steps and task assignments

**STEP 2:** *Find the best use(s) for PDC time and capacity.*

CVPDC leadership and staff should identify specific needs, opportunities, and priorities for PDC-led assistance across the region, especially those that cross local boundaries and cannot be easily addressed by existing staff among local governments.

Using this study as a guiding document, the most likely options for PDC-led coordination are the other regional policy solutions:

-   Creating a regional housing education campaign, and/or

-   Evaluating opportunities for consistency in short-term rental regulations.

Other major opportunities include, but are not limited to, the local partnership solutions also included in this report. CVPDC should propose its priorities to the newly-formed regional task force (described above) to solicit feedback and buy-in from partners.

**STEP 3:** *Expand PDC staff and/or staff capacity to support goals.*

Any substantial progress on regional housing solutions will require dedicated staffing from the PDC. This dedicated staff can be through formation of a new standalone position or through capacity and program training of existing PDC staff. Regardless of the staffing approach, this position should be dedicated to housing and community development programs.

CVPDC has three options for funding the housing and community development dedicated position. These are not mutually exclusive.

1.  Set aside existing revenue during the next budgeting cycle.

    -   PROS: Does not require external funds

    -   CONS: Could likely require shrinking other important expense areas

2.  Secure new funds from federal, state, and/or local governments. The most likely sources of these dollars include administrative set-aside funds found in housing grant awards.

    -   PROS: Does not require moving existing revenue, could be significant amounts

    -   CONS: Depends on budget levels and priorities of other public entities, may not be sustainable beyond initial grant terms

3.  Secure new funds from private donors. The most likely source would be a local philanthropic foundation (or multiple together) capable of awards large enough to support salary and expenses.

    -   PROS: Does not require moving existing revenue, could be significant amounts, probably more flexible than public grants

    -   CONS: Likely requires significant outreach and education, may not be sustainable beyond initial grant terms

**STEP 4:** *Explore regional revolving loan fund for housing.*

Nearly all new affordable housing projects in the CVPDC region---and elsewhere---face a funding shortfall even after the major sources of revenue (e.g., LIHTC) are secured. This "gap" must be filled with other grants or loans that are often smaller, but just as competitive and difficult to obtain.

In other cases, potential projects are stymied by limited funding for important pre-development activities like site surveys and infrastructure improvements. Flexible funds to support this work can be the catalyst needed to get a much-needed project off the ground.

To overcome these challenges, CVPDC should consider creating and managing a regional revolving loan fund for housing. This fund could be supported primarily by locally-generated dollars, allowing CVPDC to dictate its own terms and best meet community needs.

When ready and able, CVPDC staff can begin exploring this solution by taking the following steps:

1.  Holding preliminary and informal conversations with regional leaders and housing practitioners to determine feasibility,

2.  Seeking grant opportunities to support additional staff time or consultant help to plan and stand up the fund,

3.  Having initial conversations with other PDCs and regional entities who have implemented similar funds, and

4.  Evaluating options for stakeholder input during the fund development process (e.g., regional oversight team).

The operational steps required to fully plan and implement this fund are beyond the scope of this solution. However, completing the tasks described above will give CVPDC the best opportunity to successfully develop an important new funding source for affordable housing.

**IMPLEMENTATION PLAN**

*Immediate (0-6 months):*

Solicit invitations for a regional housing task force and schedule its first meeting. Hold internal conversations on PDC housing priorities, current staff capacity limits, and initial task force agenda. Host first regional housing task force meeting and generate specific next steps. Determine preferred approach(es) for funding new PDC housing position and hold initial conversations with potential funders.

*Short-term (6-12 months):*

Continue to support and lead regular task force meetings. Ensure the task force is focused on specific priorities and attainable objectives. Begin steps on selected regional housing solution(s), e.g. housing education campaign. (Specific tasks depend on each issue.) Take action to secure new funding for dedicated housing staff, e.g. grant applications.

*Long-term (12-24 months):*

Seek out and appoint leadership among task force members to encourage autonomy and reduce PDC responsibilities (as possible). Pending funds, hire and onboard new housing staff to manage CVPDC's housing activities. Find strategic opportunity to begin exploratory steps for the regional housing loan fund.

**RESPONSIBLE ACTORS AND THEIR ROLES**

-   CVPDC staff will sustain momentum from this study by managing the new regional housing task force, coordinating the start of regional housing solutions, and seeking additional funding to further increase the PDC's housing capacity.

-   The CVPDC board will provide high-level input on staff's efforts and help set long-term goals for housing activities. Members will help evaluate sustainable funding solutions, facilitate strong relationships with member jurisdictions, and identify new opportunities for CVPDC to address the region's housing challenges.

-   Local government representatives will participate in the regional task force and collaborate on the implementation of policy solutions.

-   Housing practitioners, service providers, and advocates will participate in the regional task force by submitting important information on their operations and client needs. These stakeholders will also likely collaborate on the implementation of policy solutions.

**LEGAL, FINANCIAL, AND ORGANIZATIONAL CAPACITY**

-   There are no known or expected significant legal barriers to the activities in this solution. However, depending on the structure of the potential regional loan fund, a new entity may need to be incorporated. This would require a minor level of attorney time and fees.

-   The primary fiscal constraint on this solution is CVPDC's current lack of dedicated funding to support the salary of a housing position. External funding opportunities are available, but are neither guaranteed nor obtainable without upfront work.

-   CVPDC has gained relevant housing policy and development experience by administering a \$2 million grant from Virginia Housing to support the creation of new affordable homes. However, until separate dedicated funds are secured for new housing staff, any tasks described in this solution will fall on current staff.

**FUNDING SCOPE REQUIREMENTS**

-   The annual cost for one new dedicated housing position will vary, depending on the level of talent and qualifications sought by CVPDC and eventually found in a preferred applicant. Based on salary ranges posted for similar open positions at CVPDC, total cost inclusive of salary and benefits for a new housing position would likely range from \$60,000 to \$90,000.

**POTENTIAL FUNDING SOURCES**

Below are possible revenue sources for additional staff capacity for housing at CVPDC.

Possible public sources:

-   "Crowd sourced" payments to CVPDC from the general funds of member jurisdictions.

-   Set aside funds to cover administration and operations in future federal and state grants, including Virginia Housing PDC housing development grants, as well as potential HOME and CDBG awards managed by CVPDC.

Possible private sources:

-   Greater Lynchburg Community Foundation

-   United Way of Central Virginia

-   Other private foundations and institutions

**METRICS TO EVALUATE SUCCESS**

Regional housing task force:

-   Number of persons on task force

-   Number of meetings per quarter/year

-   Member attendance rate

-   Number of assigned and completed tasks

PDC capacity:

-   Amount of dedicated funding secured for housing staff

-   Number of years covered by secured funds

-   Number of households/persons served or supported by programs managed by staff

**PROJECTED IMPACT**

Establishing a regional housing task force, if successful, has the potential to significantly increase knowledge sharing and collaboration among policymakers and the housing sector in the Lynchburg area. This would accelerate similar accomplishments of the Lynchburg Housing Collaborative in the city.

Securing dedicated funds to support a housing position at CVPDC would dramatically boost the region's capacity to coordinate existing efforts, initiate new activities, and leverage additional resources that support affordable housing development.

This position would also lead to a much faster exploration (and potential implementation) of a new regional housing fund. Depending on eventual funding levels, that fund could help hundreds of families obtain affordable housing each year.

::: callout-note

### West Piedmont Planning District Commission

**Approach:**

WPPDC currently has both a housing program director, a housing program specialist, and a housing rehab specialist on staff. These three positions are funded, respectively, by the Virginia Housing PDC Development Grant, a pair of grants from local philanthropic foundations, and PDC training dollars.

Of the full \$2 million PDC Development Grant, WPPDC set aside \$400,000 for future operational and administrative expenses, which includes salaries. The local private grants include \$75,000 each from The Harvest Foundation and the Danville Regional Foundation.

WPPDC is planning the following steps to sustain its housing efforts:

-   Structure the PDC Development Grant to generate future returns that will be used to create a new "Acquire, Renovate, Sell" program,

-   Create a nonprofit development corporation to unlock funding opportunities not available to public entities, and

-   Administer state- and federal-funded programs previously not deployed in the region, such as the Indoor Plumbing Rehabilitation program and lead inspection services.

**Outcomes:**

Supporting dedicated housing staff helped WPPDC efficiently deploy \$1.6 million of the PDC Development Grant to support 115 new affordable homes in the region. These investments leveraged another \$22.1 million in public and private funds. Today, WPPDC housing positions are funded through at least 2023 by their original sources. If the above strategies are successful, these positions will have sustainable funding sources.

[WPPDC Housing Initiative](https://westpiedmontpdc.org/housing/)

[WPPDC Awards Over \$1.3 Million in Affordable Housing Grants](https://westpiedmontpdc.org/2022/03/30/wppdc-awards-over-1-3-million-in-affordable-housing-grants/) (March 30, 2022)

[Local commission creates new housing position in partnership with The Harvest Foundation](https://theharvestfoundation.org/2021/11/23/local-commission-creates-new-housing-position-in-partnership-with-the-harvest-foundation-2/) (November 23, 2021)

:::

::: callout-note

### New River Valley Regional Commission

**Approach:**

NRVRC currently has a director of housing to manage the PDC's housing programs. These include:

-   The New River Valley HOME Consortium, which helps member localities access federal HOME dollars from HUD that would otherwise be much more difficult to obtain on their own. The consortium began in 2007.

-   The New River Valley Housing Trust Fund was officially announced in June 2023 and will serve as a conduit for locally-generated dollars to support additional affordable housing projects in the region. NRVRC will coordinate these awards with the HOME Consortium. The fund is currently seeded with \$2 million from the Virginia Housing PDC Development Grant.

-   Comprehensive planning and educational initiatives, such as a Housing Resource Guide and the Regional + Local NRV Housing Study, to support greater regional knowledge and collaboration on housing.

**Outcomes:**

Since 2007, the HOME Consortium has allowed projects in the region to leverage more than \$38 million additional dollars and create more than 350 new affordable homes. The NRV Housing Trust Fund represents the successful development and implementation of a flagship recommendation in the regional housing study from 2021.

The fund will make its first awards in late 2023.

[NRVRC Housing](https://nrvrc.org/housing)

[New River Valley Housing Trust Fund](https://nrvrc.org/nrv-housing-trust-fund)

:::

## Secondary solutions

### Evaluate opportunities for regional consistency for short-term rental regulations

**Issue:** *Varying approaches across localities to regulate the growing demand for short-term and seasonal rentals create a confusing policy environment*

While short-term rentals can provide a source of income for property owners and provide travelers with alternative lodging options, they can create significant challenges in the housing market. One of the most significant issues is that they can reduce the availability of housing units for long-term rental or ownership, particularly in areas with high demand for housing.

Today, localities in the region have different approaches for regulating and enforcing STRs. Some are very permissive, while others are more restrictive. This may be placing the demand burden on specific communities, such as Smith Mountain Lake, or creating pressure on localities with tighter regulations. Additionally, accurate STR counts and other data from localities are not easily accessible, leading to uncertainty on the total supply, locations, and types of STRs across the region

**SOLUTION:** *Convene a regional task force to evaluate STR policy and market dynamics*

**FRAMEWORK**

Better decisions about STR regulation will require additional collaboration and knowledge. To accomplish this, localities may explore creating a task force with the purposes of identifying specific data-sharing opportunities, compiling and evaluating all local STR policies, and finding consensus on ways to help make STRs an asset rather than liability for the region.

While each locality is keenly aware of the impacts of STRs on their local housing market, there may be a lack of understanding on how differing approaches to STRs are impacting the overall region. A regional task force of local government representatives can be brought together to discuss shared values and common concerns about STRs. In addition, a regional task force can consider hiring a consultant to study STRs across the region and provide real data to make informed decisions.

**IMPLEMENTATION PLAN**

*Immediate:*

-   **Survey existing STR regulations:** Compile all regulations pertaining to STR in each locality and assess the differences and commonalities between them.

-   **Invite local government representatives to participate:** Coordinate with member jurisdictions to identify and invite most appropriate representative(s).

*Short-term:*

-   **Hold regular meetings of a regional task force:** Discuss local and regional goals in terms of STR regulation, focusing on the impacts to the housing market, economic development, and workforce.

-   **Assess the availability of data on STRs:** Determine with regional task force whether there is enough data on STRs and its impact to make data informed decisions about appropriate regulatory stance.

-   **Determine the necessity for consulting services:** Decide with regional task force whether the availability of data and current capacity to analyze that data requires additional support from a consultant or research institution.

**LEGAL, FINANCIAL, AND ORGANIZATIONAL CAPACITY**

-   There are no legal barriers to assembling a regional task force.

-   Funding may be required if the regional task force pursues a study of STRs in the region, but there are no financial requirements of assembling a task force.

-   Regional task force assembly is dependent on local government participation and support. CVPDC staff is capable of group facilitation, but may not be able to undertake significant research and analysis tasks.

**FUNDING SCOPE REQUIREMENTS**

Dependent on decisions made by regional task force.

**POTENTIAL FUNDING SOURCES**

-   **Virginia Housing Community Impact Grants** funds can be utilized to conduct studies related to housing.

**METRICS TO EVALUATE SUCCESS**

-   The collection of standardized data on STRs across the region.

-   Completed data analysis on STRs and their impact on the region.

-   Cooperation between localities on creating a mutually beneficial STR regulatory environment.

**RESPONSIBLE ACTORS AND THEIR ROLES**

-   CVPDC staff should act as the lead organization to facilitate the regional task force

-   Local government representatives would volunteer to participate on the task force, preferably this would involve elected officials or planning and community development staff.
