# City of Lynchburg

## Primary solutions

### Use comprehensive plan update to strengthen infill development and blight remediation strategies

**Issue:** *Recent changes to city zoning and development regulations are a good start, but additional steps may be necessary to expand infill housing.*

Many parts of existing urban areas have an inefficient use of space, resulting in sprawl, a need for costly new infrastructure, and empty or underutilized parcels. The City of Lynchburg has already begun to proactively address this issue by providing infrastructure incentives and revising subdivision regulations to encourage developers to “fill out” empty parcels in existing neighborhoods.

However, as potential sites become fewer, and as the broader economic environment for residential developers may become less certain, continued progress on infill housing may begin to stall in the city.

**Solution:** *Leverage major comprehensive plan update to establish robust, systematic approach to infill housing development.*

Creating a successful infill strategy can help property owners understand their parcels’ potential, spur new investments, and increase beneficial economic activity in neighborhoods already established for development. Localities can strengthen those efforts by leveraging the data and information produced by their own departments to publish an inventory of parcels identified and promoted for residential infill.

To achieve these related goals, the city can take advantage of its upcoming comprehensive plan update process to lay out a three-pronged approach:

1. Identify and reposition “problem” properties into assets,
2. Develop property inventory to engage developers, and
3. Streamline infill development approval process.

This strategy provides detailed descriptions, recommendations, and considerations for each of these components.

**FRAMEWORK**

These three steps should be completed sequentially. However, the city should use the comprehensive planning process to determine how specific strategies are accomplished in the context of other related housing and development objectives.

::: callout-tip

### City staff capacity

Many of the tasks described below would be time and resource intensive for the city's existing staff. This limitation should be considered throughout any part of the comprehensive plan process covering this work, so that the city can decide which parts to prioritize (and fund) for staff or outside consultants to complete.

:::

**TASK 1:** Identify and reposition “problem” properties into assets.

* Continue evaluating existing blight remediation efforts already underway.
* Determine remaining legal/fiscal barriers and explore what steps are needed to overcome them.
* Collect and analyze new data to identify and prioritize vacant parcels for intervention.

**TASK 2:** Develop property inventory to engage developers.

* Create new database of properties with parcels identified in Task 1.
* Collaborate with developers to establish criteria for “infill housing potential” (lot size, utility access, etc.).
* Determine which criteria can/cannot be assessed with existing parcel data; evaluate and acquire new data if needed.
* Build out a database with parcels identified as having infill housing potential (that were not previously gathered in Task 1).
* Develop web-based application for the public to access property inventory.

**TASK 3:** Streamline infill approval process.

* Project certain scenarios onto property inventory to determine what zoning/regulatory changes might have the most significant ability to unlock parcels for development.
* Determine which of those changes could be implemented with least fiscal impact and lowest risk of (unintended) negative effects.
* Evaluate current practice of free preliminary review meetings for developers to determine whether any improvements may be needed to further streamline approval process.
* Create a design standard guide that illustrates examples of construction that fits the scale, shape, and material of existing neighborhood structures.
* If feasible, incorporate permit forms and other supplemental materials into the property inventory to create "one stop shop" for developers.

**IMPLEMENTATION PLAN**

Due to the level of work potentially required for this solution, the implementation phases are extended beyond the default 6/12/24 month windows used elsewhere in this study.

*Immediate (within 12 months):*

* Establish blight remediation and infill housing as priority issues to explore in the comprehensive plan process.
* Embed this issue into community engagement prompts used during the comprehensive plan outreach phase, particularly in use for the Diamond Hill neighborhood plan. Use this opportunity to help citizens understand scope and complexity of challenges, along with potential solutions.
* Create regular reports to monitor current blight remediation progress. Engage partners (city attorney, builders, etc.) to develop a list of challenges and opportunities.

*Short-term (within 24 months):*

* Conduct a data audit to determine what property attributes are reliably included in existing city datasets. Build out a “wish list” of desired variables that are not available and seek out new pathways to acquire and connect those data.
* Leverage the analytical work described above to map out specific objectives and strategies within the comprehensive plan framework.
  + Use outreach from that process to help accomplish the collaborative parts of Task 2.
  + Vet some of the potential streamlining strategies in Task 3 with stakeholders; recommend any and all desired solutions for inclusion in the plan.
* Evaluate whether the technical parts of Task 2 (i.e., property database and web application) could be completed by existing city departments, or whether an outside consultant is needed. If needed, begin designing an RFP for those components.
* Incorporate infill housing analysis and strategies into the first draft of the comprehensive plan.

*Long-term (within 36 months):*

* Work internally (or with consultants) to design, test, and deploy the web application described in Task 2. Proactively share the tool with city leaders, developers, and other community partners.
* Review and revise, as needed, infill housing strategies within the comprehensive plan. Adopt plan pursuant to required legislative process.
* Assemble an infill housing task force responsible for implementing, monitoring, and amending strategies. Members should include staff from relevant city departments, planning commission and/or city council, and practitioners from the private/nonprofit development sectors.

**RESPONSIBLE ACTORS AND THEIR ROLES**

City staff: Oversee and manage the comprehensive planning process, conduct analysis and report on current efforts, investigate data assets and gaps, conduct community and stakeholder engagement, interface with planning commission and city council.

City attorney: Report on current legal framework and challenges related to vacant/blighted property, review and provide opinions on proposed policy solutions. 

Planning commission and city council: Provide guidance on comprehensive plan, review and make recommendations for draft plan, adopt final plan, leverage community relationships to ensure effective stakeholder engagement.

(Optional) Consultants: Assist city staff with specific components of comprehensive plan and property analysis, design and build web application.

**LEGAL, FINANCIAL, AND ORGANIZATIONAL CAPACITY**

*Legal:*

There are no legal restrictions on any of the actions recommended to occur before and during the comprehensive planning process. However, with respect to blight remediation specifically, the city cannot go beyond any of the existing strategies enabled in current Virginia state code.

*Financial:*

The additional focus on infill housing within the comprehensive plan may require extra work beyond what may have been already budgeted for the project. Furthermore, while the legal process necessary to take or transfer ownership of blighted properties can generate substantial court and attorney fees, the long-term tax revenue generated by returning these properties to productive use would greatly exceed those one-time expenses.

*Organizational: *

Current city staff and resources (along with any planned consultant assistance) are likely fully prepared to successfully complete the comprehensive plan update. However, the additional programmatic and property-related analysis described in this solution may not be within that capacity. Similarly, a fully new interactive web application to reveal and promote infill development opportunities may be beyond staff availability and capability.

**FUNDING SCOPE REQUIREMENTS AND PROJECTED IMPACT**

Total new funding required to complete the tasks described in this solution depends on how significantly parts of that work are incorporated into staff activities already projected in the comprehensive plan budget and scope.

Contract cost for an outside consultant to complete the analytical work in Task 1 would likely fall around \$5,000, depending on scope. Contract cost for work described in Task 2, including a standalone interactive web application, could range from \$10,000 to $20,000. These are very rough estimates and should only be used to initiate further discussions prior to any RFP being drafted.

**POTENTIAL FUNDING SOURCES**

* Virginia Housing’s Community Impact Grant is purpose-built for many of the tasks included in this solution. Applications are accepted on a rolling basis. Awards range from \$15,000 to \$20,000 depending on project type.
* CDBG funds may be used for planning and capacity building activities. Allocation of any CDBG funds for this work should be planned and structured to achieve specific objectives and activities described in the City of Lynchburg 2020-2024 Five Year Consolidated Plan.
* City general funds and private philanthropic grants may also be explored as funding options.

**METRICS TO EVALUATE SUCCESS**

* Number of vacant/blighted/delinquent parcels transferred and remediated
* Number of new infill homes created
* Number of new homeowners and/or renters occupying those homes
* Total and average property value increase (and subsequent tax revenue)
* Number of citizens and stakeholders engaged on this topic within comprehensive plan process

### Preserve the existing affordable housing rental inventory

**Issue:** *Large segments of subsidized housing are aging out of their affordability commitments.*

Low-Income Housing Tax Credit (LIHTC) properties have a 30 year commitment to affordability, but only a 15 year compliance period, wherein property owners can increase rents. Nonprofit developers will often seek new allocation of tax credits before their commitment period ends, but there is often little incentive for for-profit developers to maintain affordability restrictions past the compliance period. By 2035, over 40 percent of active LIHTC units in Lynchburg are set to exit their affordability commitment period.

**Solution:** *Develop an affordable housing preservation fund to supplement federal and state resources.*

A strategic, long-term approach to preserve the city's current inventory of affordable housing would be the creation of a preservation fund, supported by city-generated revenues. This fund can provide financing options to catalyze the stabilization and recapitalization of affordable rental communities.

**FRAMEWORK**

The most substantial way for affordable housing properties to remain affordable is recapitalization via new LIHTC allocations and other significant sources of subsidy offered by the federal and state government. While local governments are generally incapable of providing comparable levels of financial assistance, they can still offer meaningful resources that increase the likelihood of those major sources being awarded and successfully applied.

Local housing trust funds (HTFs) are often used to preserve and rehabilitate affordable housing units, but they typically prioritize new construction and aid with pre-development and gap financing. Local *preservation* funds, on the other hand, are a distinct subset of HTFs to ensure that the gains in newly constructed affordable housing are not negated by the conversion of affordable units to market rate properties.

Examples of such financing programs exist in Virginia, specifically in Loudoun County, which has been facing severe housing market pressures. Fairfax County also assembled an Affordable Housing Preservation Task Force in 2020 to provide the Board of Supervisors with policy recommendations to support the preservation of affordable housing.

Affordable housing preservation funds are no different than HTFs in terms of their structure and administration. These are layered sources of funding involving public sector and sometimes private sector or philanthropic funds to capitalize a revolving loan fund. 

**IMPLEMENTATION PLAN**

*Immediate (within 6 months):*

* Assemble a comprehensive list of LIHTC properties in the City of Lynchburg, with a focus on the physical conditions of the building, subsidy expiration, number of affordable units, and ownership structure (i.e. nonprofit, for profit, etc.).
* Determine the total number of units at-risk of conversion in the next five years; make comparisons to what is currently in the development pipeline.

*Short-term (within 12 months):*

* Conduct outreach to LIHTC property owners to determine their intended plans after commitment period expiration and assess funding needed to maintain affordability.
* Educate elected city officials about the importance of an affordable housing preservation fund and how it will prevent net loss of affordable rental units in the city. Use the list of LIHTC properties and anticipated loss to help support education efforts.
* Determine the level of support that is achievable from elected officials.

*Long-term (within 24 months):*

* Identify additional sources of capital, including participation from lending institutions, corporations, and charitable foundations.
* Develop a detailed implementation model that incorporates the new sources of capital that the preservation fund will administer. Application review, scoring and selection procedures must be developed and approved by City Council.

*After first funding cycle:*

* Monitor and evaluate the fund’s performance by determining the total number of units preserved by the fund.
* Gather data on demographics of residents and other information to measure greater community impacts.
* Explore the potential for “dedicated” sources of revenue to the fund. Dedicated sources allow for greater predictability in the volume of resources and remove any fiscal cycles and shifting political priorities from affecting the operation.

**RESPONSIBLE ACTORS AND THEIR ROLES**

The key actors in this process will be the housing staff (or assigned staff) from the City of Lynchburg who would be responsible for developing this program proposal and assessing viable funding sources, programmatic design, administration, etc.

**LEGAL, FINANCIAL, AND ORGANIZATIONAL CAPACITY**

* City staff should conduct an assessment of new legal and financial liabilities that accrue from the administration of funds from new sources---including local governments, banks, corporations, and charitable institutions. When funds are provided to the fund from any of these sources in the form of grants, the fund should have a standard set of requirements that are included in the grant agreement, including clarity around liability, lending, and grant making procedures, procedures and reporting.
* City staff should evaluate staff capacity to add new products and procedures.  If private funding requires traditional bank style “underwriting” then there may be a need for training or the outsourcing of certain elements of the loan/grant origination process.
* Similarly, if loan servicing, including collection and application of payments, is part of an expanded fund, that will also involve software and accounting upgrades as well as staff training. These functions could also be outsourced to a lending institution, or to Virginia Community Capital (Virginia’s statewide CDFI), or similar partner.

**FUNDING SCOPE REQUIREMENTS**

Given the scale of housing needs in the City of Lynchburg, we recommend that the goal for preservation fund capitalization be at least $1 million per year. Most housing trust funds in the state are capitalized at levels that meet or exceed this amount.

**POTENTIAL FUNDING SOURCES**

**City-generated funds:**

* The most common source of funding for local housing trust funds is a general fund appropriation from the locality. While the “gold standard” for affordable housing funds is a “dedicated” revenue source from a fee or tax, that approach is not the standard across Virginia.
* Currently, most trust funds in Virginia are funded with combinations of local general fund appropriations and federal housing funds, with some localities also incorporating dedicated revenue sources as a partial income stream.
* Another long-term solution may be issuing general obligation (GO) bonds for a substantial investment that could stretch across multiple years.

**Private and philanthropic sources:**

* A wide range of nonpublic funding sources have supported affordable housing funds around the state and the country. These include banks and other financial institutions that provide loan and grant funds.
* Corporations, philanthropic foundations, and other community anchor institutions, including hospital systems, colleges and universities, and churches can be substantial partners.

With regard to the mix of grants and loans, any affordable housing fund that can secure a greater level of grant funding compared to loans will have greater flexibility in terms of the needs that it serves as well as its attractiveness to the affordable housing development community. Loan funds may be available from a wide range of actors—for example, Virginia Housing and Virginia Community Capital both provide loan funds on favorable terms for affordable housing developments.

We recommend not bypassing local lenders in favor of working strictly with state sources. Local lenders will frequently be able to tailor their lending specifically to local needs and align with other affordable housing fund resources. State sources will be especially useful as a significant element of the capital stack needed to develop affordable projects in the region, but they will conform to a statewide standard. 

**METRICS TO EVALUATE SUCCESS**

A critical element for a successful affordable housing fund is to be able to measure both outputs and outcomes. 

**Outputs:** It is important to collect data on the number of housing units preserved, their location, cost and other relevant data points. While these metrics may not materialize until the second or third year after the first allocations, such data is necessary.

**Outcomes:** It is just as, if not more, important to measure who is being helped and assess whether objectives are accomplished. This information is more difficult and time-consuming to collect but is crucial to sustaining funder commitment in the long run.

**PROJECTED IMPACT**

Based upon anticipated funding levels, the fund should set preservation goals for a 3-5 year period. Because of the often lengthy periods of time to close on acquisitions or obtain gap financing, these projects will frequently carry over from one year to the next. 

**EXAMPLES AND BEST PRACTICES**

::: callout-note

### Loudoun County Rental Housing Acquisition and Preservation Loan Program

The [Loudoun County Rental Housing Acquisition and Preservation Loan Program](https://www.loudoun.gov/5705/Rental-Housing-Acquisition-Preservation-) was created in early 2022. The program acts as a gap lender to help finance the acquisition and preservation of existing multifamily rental developments in the County.

The program is administered by the Loudoun County Department of Housing and Community Development. Requirements placed on the funding include a set percentage of units designated as affordable (20% of total units affordable at 50% Area Median Income (AMI) or 40% of total units affordable at 60% AMI. In addition, the County places a 30-year affordability commitment on properties utilizing the fund.

The source of funds for the initial capitalization of the RHAP fund was the FY 2021 Fund Balance from Loudoun’s existing Housing Fund, \$5 million. Staff has since recommended that a portion of the FY 2023 real property tax rate be dedicated to the RHAP program, approximately \$6.5 million.

:::

## Secondary solutions 

### Continue the work of Lynchburg Housing Collaborative 

**Issue:** *Through the work of the regional housing collaborative, Lynchburg municipal staff and housing organizations have provided city council policy ideas to create more home ownership and affordable rentals opportunities and address the need for more affordable housing throughout the entire city. To date, some recommendations are yet undeveloped or still being explored.*

The Lynchburg Regional Housing Collaborative was established with the support of the city council to: 1) Create a detailed analysis of the current housing market, 2) assess the challenges faced by lower and middle-income households, and 3) examining the potential efficacy and impact of the proposed policies. Following their 2019 report to council, some priorities and policies remain undeveloped and are an avenue for continued policy growth.  

**Solution:** *Pursue recommendations made through the collaborative that address the priority of increasing housing opportunity for all income levels.*

Acheiving these objectives should also further build the collaborative through targeted recruitment, which may include representatives from lending institutions, private residential developers, and other anchor institutions.

This solution will focus on the collaborative's recommendation to explore an inclusionary housing program for the city. Also known as affordable dwelling unit (ADU) programs, they incentivize the creation of below-market rate units within new residential development in exchange for density bonus and other benefits to offset costs.

**FRAMEWORK**

Housing shortages and the lack of affordable options present significant obstacles to community development and stability. Inclusive and diverse communities are advantageous not just for the individuals who benefit, but for the community as a whole. Communities that strive to include a wide range of household types have been shown to foster entrepreneurship, community-based economic activity, and educational improvement. Adopting inclusionary housing practices and diversifying the regional housing collaborative’s membership to increase stakeholder engagement are primary strategies to build from existing policy groundwork. 

**Comparison of enabling legislation**

Virginia state code includes three sections governing the ability of localities to establish ADU programs:

* [§ 15.2-2304](https://law.lis.virginia.gov/vacode/title15.2/chapter22/section15.2-2304/): Grants applicable jurisdictions wide power to require ADUs in almost all new residential projects that require special approval, as long as commensurate density bonuses and other incentives are provided as optional measures to offset costs. Lynchburg is *NOT* one of the seven jurisdictions enabled by this statute.
* [§ 15.2-2305](https://law.lis.virginia.gov/vacode/title15.2/chapter22/section15.2-2305/): Grants all other jurisdictions the power to adopt an ADU program that allows density bonuses and other incentives to be offered in exchange for affordable units, but developers are *NOT* required to participate. The statute also limits certain program design elements, such as capping density bonuses and affordability set-asides at 30 and 17 percent, respectively.
* [§ 15.2-2305.1](https://law.lis.virginia.gov/vacode/title15.2/chapter22/section15.2-2305.1/): Uses almost identical applicability standards as § 15.2-2305, but expands and enumerates in more detail the scope of powers afforded to localities. However, these additions are fairly prescriptive and potentially burdensome, depending on market conditions.

Historically, the only successful ADU programs in Virginia have been established under § 15.2-2304. Only a few localities under § 15.2-2305 have pursued or adopted an ADU program; none of those in place have produced a meaningful number of units. As of October 2023, no locality has adopted a program under § 15.2-2305.1.

Across all ADU programs in Virginia, the primary mechanism to avoid constitutional takings challenges is the density bonus. These bonuses, generally expressed as a percent increase in allowable units relative to the base zoning, are awarded commensurately with the share of below-market units set aside by the developer. In theory, the added economic value of more units will offset the rental income “forgiven” by the provision of units leased at below-market prices.

Ordinances establishing ADU programs will enumerate the ratios used to calculate the density bonus. While localities under § 15.2-2304 can freely set density bonus ratios, § 15.2-2305 and § 15.2-2305.1 both apply restrictions.

The chart below shows the differences in these amounts between each statute.

```{r}
#| label: fig-va-adu
#| fig-cap: "Allowable ADU program design limits in Virginia state code"

library(tidyverse)
library(scales)
library(hdatools)
library(ggtext)

adu <- read_rds("data/adu.rds")

ggplot(adu,
       aes(
         x = affordable,
         y = density,
         color = code,
         fill = code
       )) +
  geom_line(linewidth = 1.5) +
  geom_area(alpha = 0.2) +
  geom_ribbon(
    aes(
      xmin = 0,
      xmax = affordable
    ),
    alpha = 0.2,
    linewidth = 0
  ) +
  facet_wrap(
    ~fct_reorder(
      code,
      density
      )
    ) +
  scale_color_hfv(-1) +
  scale_fill_hfv(-1) +
  scale_x_continuous(
    labels = label_percent(accuracy = 0.1),
    breaks = c(0.05, 0.1, 0.17, 0.35),
    limits = c(0,0.4),
    expand = expansion(mult = c(0,0))
    ) +
  scale_y_continuous(
    labels = label_percent(accuracy = 0.1),
    breaks = c(0.2, 0.3, 0.575, 0.95),
    limits = c(0,1),
    expand = expansion(mult = c(0,0))
  ) +
  add_zero_line("x") +
  add_zero_line("y") +
  coord_fixed(ratio = 0.5) +
  labs(
    title = "Allowable ADU program design limits in Virginia state code",
    subtitle = "Minimum and maximum density bonus and affordable unit percentages",
    x = "\nAffordable units",
    y = "Density bonus\n",
    caption = "**Source:** Va. Code Ann. § 15.2-2305 and § 15.2-2305.1."
  ) +
  theme_hfv() +
  theme(
    plot.title = element_textbox(size = 11),
    plot.subtitle = element_textbox(size = 9),
    axis.title = element_text(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    panel.grid.major.x = element_line(color = "#cbcdcc", linewidth = 0.05)
  )

```

Ratios in § 15.2-2305.1, however, differ from § 15.2-2305 in two important ways:

* Specific ratios are itemized in tables to list the full range of options, and
* Unique ratio tables are applied according to the income served by the ADUs.

The first option under § 15.2-2305.1 is for low-income units, defined in the code as 80% of Area Median Income (AMI) and below. Density bonuses range from 20% to 57.5% for affordable unit set-asides between 10% and 35%.

Alternatively, a developer may provide units for very-low-income households, or those earning 50% AMI and below. Density bonuses range from 20% to 95% for affordable unit set-asides between 10% and 35%. The greatly increased density allowances reflect the need to offset the reduction in rental revenue from the more deeply-targeted affordable units.

**Important takeaways**

Along with a solid understanding of the density bonus and affordability mechanisms described above, collaborative members should also consider the following points when weighing an ADU program for Lynchburg:

* How to strategically integrate the policy's design into future zoning goals regarding density,
* How to incorporate additional incentives, if desired, to potentially include fee waivers, lowered parking requirements, and other benefits to lower development costs,
* How to enforce the affordability and income limits of set-aside units,
* Whether the program may also be applicable to larger single-family developments where homes are sold, and not rented, and
* What structures are needed to amend program elements should broader economic conditions affect development costs and affordability.

**IMPLEMENTATION PLAN**

*Immediate (within 6 months):*

* Review and assess options under both § 15.2-2305 and § 15.2-2305.1 to determine which option may be more applicable.
* Use the findings from this study, along with updated affordability analysis as needed, to determine what income ranges should be prioritized.
* Plan for how inclusionary housing policies could be tied to other priorities, such as transportation access.
* Engage anchor health and education institutions to join the housing collaborative.

*Short-term (within 12 months):*

* Conduct outreach to housing officials from Fairfax County, Loudoun County, and the City of Alexandria. These localities have longstanding inclusionary zoning ordinances created under §15.2-2304. Seek guidance on the following:
  + Administration needs and capacity.
  + Best practices for outreach to developers and builders.
  + Data tracking and reporting.
  + Methods to build-in programmatic flexibility and resiliency.
* Make the case for addressing affordable housing needs and illustrate how an inclusionary housing program would begin to solve the problem. Outreach efforts should address common questions like: 
  + What is inclusionary housing?
  + Why do we need inclusionary housing?
  + Why is inclusionary housing useful?

*Long-term (within 24 months):*

* Draft a full ordinance and gather feedback from stakeholders in formal and informal settings.
* Assess the ordinance’s potential impact on developable land in the town. Learn the opinions and projections of builders and developers.
* Consider pursuing legislative action in the General Assembly to join the localities authorized to adopt stronger ADU ordinances under § 15.2-2304.

**RESPONSIBLE ACTORS AND THEIR ROLES**

* Local planning staff will help draft and design the ordinance, with significant guidance from the Lynchburg Housing Collaborative.
* Planning Council and City Council will review drafts, provide feedback, and adopt the final version.
* Developers and builders will provide meaningful input and conduct provisions in the ordinance to add affordable units to new construction.
* Technical consultants may be a useful resource to help design and draft the policy.

::: callout-note

### Moderately Priced Dwelling Unit Program - Montgomery County, MD

**Approach:**

Montgomery County operates one of the most established inclusionary zoning policies in the nation. Their Moderately Priced Dwelling Unit (MPDU) program mandates that 12-15% of units in new residential developments are reserved for affordable housing.

**Outcomes:**

Since it was established in the 1970s, over 11,000 affordable units have been created in the county through the MPDU program and through developer incentives including a waiver of water, sewer charge and impact fees. 

:::
