# Engagement and outreach {#part-1-2}

From December 2022 to February 2023, HousingForward Virginia conducted meetings with local government officials, as well as focus groups of housing practitioners, from communities served by the Central Virginia Planning District Commission.

The findings from this engagement are foundational context for the analysis and solutions that will follow in the full regional report. Participants' responses were organized into four sections: housing market dynamics, challenges and needs, service provision, and proposed solutions.

## Key highlights

**Housing market dynamics**

Housing demand outstrips supply in the Central Virginia region in nearly all sectors of the market. This dynamic has led rents and home prices to surge. Local residents are increasingly outbid by newcomers from larger metro areas who are relocating and have higher purchasing power. Affordable options for low-income renters are now disappearing, leading to increased housing insecurity.

**Challenges and needs**

A wide range of regulatory, economic, and political barriers prevent new housing from being easily produced today. Local governments only have control over some of these areas---notably land use---but have room to make improvements. Some challenges, such as limited senior housing options and an accelerating short-term rental market, will require unique solutions.

**Service provision**

Housing agencies and nonprofit providers are doing good work, but their current capacity is far below the current (and growing) needs of low-income renters, homeowners, and persons experiencing homelessness.

**Proposed solutions**

Participants' ideas for improving housing opportunities included (but were not limited to) new messaging strategies, expanding cross-sector collaborations, reducing zoning barriers, and generating new locally-funded housing assistance programs.

# Engagement completed

## Locality kick-off meetings

In December 2022, HousingForward Virginia and CVPDC staff met with representatives from local governments across the region. These kick-off meetings were an opportunity for HFV to learn about housing-related issues and questions that localities would like to see addressed in the study. The following local governments and organizations were represented at these meetings:

-   Town of Alta Vista
-   Amherst County
-   Amherst County Service Authority
-   Amherst County Adult Protective Services
-   Town of Amherst
-   Appomattox County
-   Town of Appomattox
-   Bedford County
-   Town of Bedford
-   Town of Brookneal
-   Campbell County
-   City of Lynchburg

## Focus groups

Following HousingForward Virginia's visit to the region to attend kick-off meetings with local government, a series of virtual focus group sessions were held to hear from other organizations, businesses, and professions connected to housing in the CVPDC.

Four focus groups were held from the end of January into the month of February, and included the following parties, with some attending multiple sessions:

::: {layout-ncol="2"}
Real estate and listing agents

-   Karl Miller Realty
-   Kathy Carlson Realty
-   Mark Dalton Realty

Housing/service providers

-   James River Housing Partners
-   Thalhimer
-   Lynchburg Community Action Group
-   Lighthouse
-   Central Virginia Alliance for Community Living
-   Greater Lynchburg Habitat for Humanity
-   Lynchburg Redevelopment and Housing Authority
-   Piedmont Community Impact
-   Miriam's House
-   Bedford Housing Coalition
-   Legal Aid Society -- Lynchburg

Homebuilders and developers

-   Amherst County Habitat
-   Scott Insurance
-   NRV Builders/Ryan Homes
-   AC Capital, LLC
-   NRV Builders
-   Perrow Corporation
-   Gerdy Construction Company

Employers

-   Campbell County Schools
-   Georgia-Pacific Corporation
-   Fleet Laboratories
-   Liberty University
-   BWX Technologies
-   Centra Health
-   Foster Fuels
-   Randolph College
:::

A total of 56 individuals were engaged through these discussions. Input from these focus groups helped diversify insights into the current conditions and challenges facing the region's housing. These talks, in combination with the locality meetings, helped identify overarching themes described in the following sections.

## Housing market dynamics

All parties engaged for this study were first asked to describe the current conditions of the housing market in the region. Eight different themes emerged from their responses.

**The overall housing supply is not keeping pace with demand in the region.**

Nearly all participants described an acute shortage of available affordable and market rate housing. This is particularly true for single-family housing, with affordable options (generally described as homes priced under $250,000) largely missing or snatched up quickly.

This has meant first-time buyers in particular have had a difficult time finding their ideal housing, forcing them to remain in their unpreferred situation (i.e. renting or living with family) longer than they desire.

Outside of Lynchburg, finding a diversity of housing options is difficult. Many places lack the types of housing that would help attract young professionals and graduates, which presents a long-term challenge for an otherwise aging local population. 

**Housing affordability in the region is directly influenced by broader state and national economic trends.**

The Central Virginia region has not been immune to the same macroeconomic forces affecting housing markets elsewhere since 2020. These trends include:

1. Increased migration from higher-income areas due to working professionals and retirees looking for more affordable options.
2. Supply chain and labor shortage issues stalling housing construction.
3. Growing housing instability as pandemic-era rental assistance and eviction prevention measures have expired.
4. Rising interest rates in 2022 forcing many first-time homebuyers back onto the sidelines.

Each of these factors has contributed to rising housing costs across the area.

**Four distinct groups of homebuyers often compete against each other.**

Participants outlined four types of buyers in the region today. While some have specialized needs, many are looking for similar opportunities and driving up prices.

1. First-time buyers 

* Participants found clear consensus that a single-income earner from the area cannot buy a single family home in the current market. This impacts first-time buyers more than the other categories of buyers, who typically have less savings and are recent graduates or early in their careers.
* Some homebuyers who purchased when interest rates were still low are opting to keep or transition their properties as rentals rather than selling, further impacting the amount of available single-family homes that would normally be ripe for first-time buyers.

2. Relocation buyers

* Many new buyers are relocating to the Central Virginia region from larger metro areas, both within the state and from the Northeast. This migration began in earnest during the pandemic with the rise of work from home options.
* Buyers coming from these larger markets often purchase homes upfront with cash and are able to afford home prices that are typically unaffordable to local residents. Participants noted that these buyers are purchasing homes both as primary residences as well as investment properties.

3. Upsizing/downsizing families

* The influx of relocating retirees and as well as locals aging in place has meant a large portion of the region’s population is looking for attractive downsizing options. This has increased demand for single-level patio-style homes and homes with lower maintenance needs.
* At the same time, there are young couples and families looking to “upsize” their current apartment or townhome, according to some participants. These households are likely to place a high value on proximity to their jobs and childcare options.

4. Investors

* The influx of remote workers and retirees from higher-wealth areas has resulted in growing investment property activity.
* Focus groups identified several common types of investors, including parents of university students who purchase a home for their child (and roommates) to rent, and wealthy out-of-state buyers securing vacation rental properties around Smith Mountain Lake.
* These purchasers often beat out other families and first-time buyers in a limited housing inventory and high-demand market.

**Homebuilders are doing their best to create products that meet changing demand.**

The growing demand for townhomes and other options for entry-level buyers is well understood by both developers and localities. Participants provided numerous examples of recently completed, in-progress, and proposed townhome developments in every locality. These included single- and multiple-lot infill projects as well as village-style greenfield developments.

Anecdotally, new homes of this type were described as priced around \$250,000 to \$275,000, and marketed to both young and old buyers.

**New manufactured homes are filling the vacuum for affordable homeownership options in lieu of other options.**

Outside of the immediate Lynchburg area, newly placed manufactured homes are satisfying demand for low-cost homes, according to many local government officials. Most of these homes are purchased directly from the manufacturer (e.g. Clayton Homes) and placed on rural lots. Including land, total costs can be around $150,000—much lower than other traditionally-built new homes in the region.

**Faced with accelerating prices, low-income renters have few options.**

A major theme repeated throughout all conversations was the persistence of COVID-era economic impacts on the region’s renters. Rents have risen to an all time high due to increased demand and limited supply, while local wages have remained largely static. This has left many renters, especially those on fixed incomes, increasingly cost burdened.

Service providers also shared that more barriers to housing have appeared since the pandemic. Landlords have started to require higher deposits or income limits, which disqualify many low-income renters—even those with Housing Choice Vouchers.

**The lack of low-cost housing is leading to an increase in homelessness across the region.**

Both local officials and focus group participants shared major concerns about the growing prevalence of homelessness and housing insecurity over the past year. This was directly attributed to increased housing costs and near-zero availability of deeply affordable homes.

In Lynchburg, the overall number of persons experiencing homelessness was noted as stable or possibly declining. However, participants from suburban and rural areas consistently reported increasing rates of “hidden” homelessness. This includes persons living in cars, tents, campers, and motels, as well as those doubled-up with another household.

**Broadband access significantly influences the housing choices of both existing and new residents.  **

Reliable high-speed internet is a necessity for many households in 2023. They need access for work, school, healthcare, and entertainment. As a result, broadband is now a required amenity for just about every homebuyer in the region, regardless of their origins.

Recent expansions of broadband service in many of the relatively dense areas, especially around Smith Mountain Lake, has contributed to higher demand and escalating prices. This has often come at the expense of existing residents, who have less purchasing power than newcomers from Northern Virginia and other wealthier areas.

## Challenges and needs

Participants shared their perspectives on the primary challenges and needs found in the region’s housing market today. Their feedback was organized into seven themes.

**Opposition to new housing prevents both local and regional solutions to address residents’ needs.**

Many participants decried an enduring refusal to take steps toward housing affordability in multiple communities. This opposition can be common among existing residents, as well as some elected officials. Misguided fears over home values, crime, and traffic are regularly cited as reasons to reject new housing, especially denser options that are more affordable by design.

Fragmented philosophies on growth and development have also prevented a regional vision for housing from forming. While some localities are actively finding ways to attract new residents, others want the opposite. In some cases, these preferences are at odds with broader market and demographic forces.

**Worsening availability and affordability of housing in the region is actively impeding economic development goals.**

Across the board, participants made the case that the limited supply of housing options in Central Virginia is now stymying ongoing economic development efforts. Major employers, including many local governments, described the challenges their employees have faced searching for housing. High-earning executives and lower-wage workers alike are finding it increasingly difficult to find a satisfactory home. 

As a result, many local economic development officials are beginning to make housing a priority. They fear that the employers and jobs they want to attract to strengthen and diversify their workforce will begin to pass over the region for other areas with better housing availability. This concern also extends to the region’s organic workforce of high-school and college graduates who are increasingly unable to afford to live in their hometowns.

**Developers must overcome a range of regulatory and financial challenges to successfully build homes in Central Virginia.**

Based on conversations with builders, local officials, and other stakeholders, five distinct barriers were identified as challenges to the development of new homes.

1. Land use and zoning 

* Many large housing developments in the region, whether single-family or apartments, have to complete a public entitlement process that introduces additional costs and delays. This process also requires public hearings, where small but loud groups of residents can lobby against new housing.
* Certain development requirements in local zoning ordinances can also have outsized impacts. For example, the Town of Bedford requires a full site plan approval before rezoning—which some developers called a nonstarter.

2. State environmental and transportation regulations 

* In some parts of the region, especially smaller towns like Amherst, local zoning requirements are not a barrier at all. Instead, despite strong efforts by staff to attract new residential development, state environmental and transportation regulations that apply to larger-scale plans prevent proposals from penciling out.
* Runoff abatement, road infrastructure, and other requirements were all cited as major challenges to development for infill sites within towns. As a result, developers will instead build on the edges of suburban markets, where greenfield sites are cheaper and easier to develop.

3. Supply chain issues and labor shortages 

* Developers explained how post-COVID supply chain issues continue to impact access to, and costs of, needed materials. This, in turn, lengthens development timelines and adds onto costs—both of which increase prices.
* There was also consensus that the labor force and vendor network needed to handle the volume of housing demand is missing. While the region has an abundance of college students, it is missing skilled trade education, resulting in plumbers and electricians coming to serve the region from as far as Richmond or Northern Virginia.
* In Lynchburg, the current scale of tract-like production of multifamily townhomes has sapped the local pool of contractors and subcontractors, making it harder to address the demand for other forms of housing.

4. Gaps in public infrastructure 

* In the greater Lynchburg area, water and sewer capacity is a hard limit on where developers can build homes.
* While public authorities are actively working to expand these services, they are challenged by a concurrent need to replace existing lines at the end of their lifespan, as well as increasing difficulties securing funds to cover this work.

5. Rising interest rates

* Developers were candid about the impacts changing interest rates and the recovering economy has had upon their work. Prior to summer 2022, when rates were still at historic lows, many developers and investors looked to expand their portfolios through both new construction and acquisitions.
* As rates have since increased, construction and major rehab work has slowed down—despite demand remaining.

**Desirable housing options for aging residents are hard to find.**

Focus groups discussed the increasing demand for patio homes and single-story homes for seniors to age in place. This confirmed ongoing demographic trends found in analysis of existing regional plans that show a need to accommodate an aging population.

Real estate agents also noted that the region is marketed as a retirement community to those living in Northern Virginia, Virginia Beach, and Maryland, which has attracted more older adults looking for options that suit their needs.

While participants provided several examples of new patio-style developments in different parts of the region, they cautioned that not all were to be age-restricted, and that this new supply is still far below demand.

An aging population also means growing numbers of older residents passing away or moving into assisted living homes. When this happens, they leave their homes in varying conditions that can make it difficult to readily re-list them on the market. Some participants suggested that homeowners looking to weatherize or repair older homes often face tangled titles or ownership issues that can prevent needed maintenance. 

Finally, some participants shared a desire to see more multigenerational dwelling options in the region, whether through accessory dwelling units (ADUs) or just by intentional development in areas better connected to social and medical services.

**Renters with the lowest incomes face the poorest housing conditions.**

High demand and low supply of homes affordable to low-income households has allowed some landlords to delay much-needed improvements to their units. Participants described this dynamic as most prevalent in mobile home parks, parts of Lynchburg, and in some smaller towns.

In many of the region’s mobile home parks, rents have risen significantly, despite the large share of old units built prior to universal safety standards set by HUD in 1976. These homes are well beyond their functional lifespan and often have chain of title issues.

Anecdotally, focus group participants shared that many Lynchburg renters avoid pushing for needed improvements to their homes, for fear of retaliation or blacklisting by the limited landlord options in the area. Town representatives also discussed problems with slumlords keeping their properties in undesirable conditions, despite pleas from tenants and town staff alike.

These problems contribute to growing instances of overcrowding and homelessness in the region. When renters have so few options, they will often be forced into motels, doubling up in cramped single-wide mobile homes, or resorting to living out of their car.

**Localities do not have the right tools to solve housing quality problems.**

Even when local governments are eager to reduce blight and improve housing quality, they are hampered by both legal and capacity issues. Representatives from several towns shared their frustration with state code restricting their ability to enforce building and maintenance codes.

Furthermore, legal barriers notwithstanding, towns and some counties in the region all stated that they do not have the proper staffing to regularly inspect properties and enforce requirements they already have on the books.

In Lynchburg, however, city officials are expanding funds and staff capacity to go after tax delinquent properties that have been vacant for a long period. Still, because this process is governed by Virginia state code, city officials noted certain ways they remain unable to address the full range of problem properties.

**Short-term rentals are booming—and inconsistently regulated.**

Demand for short-term rentals (STRs) across the region has increased significantly over the past several years. Much of this demand can be attributed to recreational tourism in Amherst County, vacationers at Smith Mountain Lake, and visitors to Liberty University.

Despite their increased prevalence, STRs are not consistently regulated by localities across the region. For example, Campbell County requires an SUP for all STRs and limits the number of visitors during a stay. Bedford County, on the other hand, now has much looser restrictions—leading to the number of STRs in the county to increase from 200 to 450 during the pandemic.

## Service provision

Participants were asked to describe the current ability of housing service providers to meet residents’ needs. They identified four major takeaways.

**The current capacity of nonprofit providers is insufficient to support the growing needs of low-income renters.**

Local service providers mentioned the expanding needs of their clients and the severity of housing issues facing low-income people in the area. While nonprofits and local churches have attempted to help renters get caught up on debts from COVID, they reported feeling that “pockets aren’t big enough” to meet the financial need in our engagement sessions. This is particularly true for clients that require braided resources, creating a juggling process for service providers who can only help fund or support for partial services.

Service providers shared that clients have experienced job losses, medical emergencies, or a need to support family and children out of school that has resulted in unpaid rent growing to levels beyond their ability to assist. As in other parts of the Commonwealth, renters have experienced a misunderstanding of what the eviction moratorium meant in terms of their rental debt continuing to accrue. Some providers anecdotally cited an average of $7,000 as the back rent facing many low-income renters.

The Lynchburg Redevelopment and Housing Authority shared their efforts to keep families housed, including extending time on existing Housing Choice Vouchers to help families struggling to find options. Rising rental rates and persisting stigma against HCV holders has resulted in some landlords refusing low-income renters and finding a way around state law that prohibits this type of discrimination.

Clients with compounding special service or accessibility needs, who require more than what LRHA can provide, turn to unsafe or less than ideal housing options offered to them in a tight rental market. While the City of Lynchburg has a rental inspection program and other initiatives intended to help clear out unsafe housing with their enforcement mechanisms, in practice, multiple focus group attendees voiced a desire to see the city use these tools to the full extent.

**Home repair and rehab work is admirable, but scattered and insufficient.**

Nonprofit developers are seeing a dramatic increase in home repair needs as homeowners defer maintenance due to financial hardship and a lack of support measures. A wide assortment of nonprofits and community organizations (including Habitat for Humanity affiliates and local church groups) are working to meet these needs, but there appears to be little coordination among providers, and demand far exceeds their current capacity.

One bright spot is the Town of Altavista, which is using DHCD’s Acquire, Renovate, Sell (ARS) program to turn problem properties into new affordable homeownership opportunities. The Claire Parker Foundation is also working independently to “flip” blighted homes in the town.

**Providers cannot adequately measure and address housing instability outside of the city.**

While participants considered the Continuum of Care well-connected for homeless service providers in the region, they added that there are still not enough affordable housing options to help people permanently exit the homelessness system.

Tracking the struggles of the county residents, particularly for indicators of instability and homelessness, is also an ongoing challenge for service providers. Many focus groups discussed the hidden homelessness problem outside of Lynchburg, which appears in the form of overcrowded single-wide trailers and doubling-up with extended families.

Another part of the difficulty in serving vulnerable populations in the region is transportation and accessibility challenges. In rural areas, individuals are so spread out that providing needed medical and social services becomes a challenge, something particularly important to the increasingly aging population of the region.  

**Missing social infrastructure, like affordable childcare and transportation, places further limitations on housing choice and workforce development. **

Participants regularly described how the lack of important social infrastructure places artificial limitations on where many families can live and work, especially outside of the immediate Lynchburg area. The two issues consistently raised were childcare and transportation.

The limited number of affordable and accredited childcare options requires parents to make certain sacrifices, such as forgoing work shifts to watch their children, or living doubled-up with extended family so they can provide childcare.

Likewise, limited transportation options can stifle workers and families from thriving. One participant called attention to many industrial jobs that require Sunday shifts being out of reach for those without cars because public transportation options are reduced on Sundays.
