# City of Lynchburg

## Primary Solutions

### Use comprehensive plan update to strengthen infill development and blight remediation strategies

Issue: Recent changes to city zoning and development regulations are a good start, but additional steps may be necessary to expand infill housing 

Many parts of existing urban areas have an inefficient use of space, resulting in sprawl, a need for costly new infrastructure, and empty or underutilized parcels. The City of Lynchburg has already begun to proactively address this issue by providing infrastructure incentives and revising subdivision regulations to encourage developers to “fill out” empty parcels in existing neighborhoods.
However, as potential sites become fewer, and as the broader economic environment for residential developers may become less certain, continued progress on infill housing may begin to stall in the city.

Solution: Leverage major comprehensive plan update to establish robust, systematic approach to infill housing development

Creating a successful infill strategy can help property owners understand their parcels’ potential, spur new investments, and increase beneficial economic activity in neighborhoods already established for development. Localities can strengthen those efforts by leveraging the data and information produced by their own departments to publish an inventory of parcels identified and promoted for residential infill.
To achieve these related goals, the city can take advantage of its upcoming comprehensive plan update process to lay out a three-pronged approach:
Identify and reposition “problem” properties into assets,
Develop property inventory to engage developers, and
Streamline infill development approval process.
This strategy provides detailed descriptions, recommendations, and considerations for each of these components.

FRAMEWORK

These three steps should be completed sequentially. However, the city should use the comprehensive planning process to determine how specific strategies are accomplished in the context of other related housing and development objectives.
[NOTE: Many parts of the tasks below can be expanded with more detail if desired. City staff should advise HFV on which items, if any, they would like to see built out further.]
TASK 1: Identify and reposition “problem” properties into assets.
Continue evaluating existing blight remediation efforts already underway.
Determine remaining legal/fiscal barriers and explore what steps are needed to overcome them.
Collect and analyze new data to identify and prioritize vacant parcels for intervention.
TASK 2: Develop property inventory to engage developers.
Seed new database of properties with parcels identified in Task 1.
Collaborate with developers to establish criteria for “infill housing potential” (lot size, utility access, etc.).
Determine which criteria can/cannot be assessed with existing parcel data; evaluate and acquire new data if needed.
Build out a database with parcels identified as having infill housing potential (that were not previously gathered in Task 1).
Develop web-based application for the public to access property inventory.
TASK 3: Streamline infill approval process.
Project certain scenarios onto property inventory to determine what zoning/regulatory changes might have most significant ability to unlock parcels for development.
Determine which of those changes could be implemented with least fiscal impact and lowest risk of (unintended) negative effects.
Identify opportunities to allow for pre-approval of certain development steps if the application clearly meets established criteria.
Integrate permitting steps/info into property inventory to reduce the number of steps and contact points needed to acquire approval.

IMPLEMENTATION PLAN

Immediate:

Establish blight remediation and infill housing as priority issues to explore in the comprehensive plan process.
Embed this issue into community engagement prompts used during the comprehensive plan outreach phase. Use this opportunity to help citizens understand scope and complexity of challenges, along with potential solutions.
Create regular reports to monitor current blight remediation progress. Engage partners (city attorney, builders, etc.) to develop a list of challenges and opportunities.

Short-term:

Conduct a data audit to determine what property attributes are reliably included in existing city datasets. Build out a “wish list” of desired variables that are not available and seek out new pathways to acquire and connect those data.
Leverage the analytical work described above to map out specific objectives and strategies within the comprehensive plan framework.
Use outreach from that process to help accomplish the collaborative parts of Task 2.
Vet some of the potential streamlining strategies in Task 3 with stakeholders; recommend any and all desired solutions for inclusion in the plan.
Evaluate whether the technical parts of Task 2 (i.e., property database and web application) could be completed by existing city departments, or whether an outside consultant is needed. If needed, begin designing an RFP for those components.
Incorporate infill housing analysis and strategies into the first draft of the comprehensive plan.

Long-term:

Work internally (or with consultants) to design, test, and deploy the web application described in Task 2. Proactively share the tool with city leaders, developers, and other community partners.
Review and revise, as needed, infill housing strategies within the comprehensive plan. Adopt plan pursuant to required legislative process.
Assemble an infill housing task force responsible for implementing, monitoring, and amending strategies. Members should include staff from relevant city departments, planning commission and/or city council, and practitioners from the private/nonprofit development sectors.

RESPONSIBLE ACTORS AND THEIR ROLES

City staff: Oversee and manage the comprehensive planning process, conduct analysis and report on current efforts, investigate data assets and gaps, conduct community and stakeholder engagement, interface with planning commission and city council.
City attorney: Report on current legal framework and challenges related to vacant/blighted property, review and provide opinions on proposed policy solutions. 
Planning commission and city council: Provide guidance on comprehensive plan, review and make recommendations for draft plan, adopt final plan, leverage community relationships to ensure effective stakeholder engagement.
(Optional) Consultants: Assist city staff with specific components of comprehensive plan and property analysis, design and build web application.

LEGAL, FINANCIAL, AND ORGANIZATIONAL CAPACITY

Legal:
There are no legal restrictions on any of the actions recommended to occur before and during the comprehensive planning process.
However, with respect to blight remediation specifically, the city cannot go beyond any of the existing strategies enabled in current Virginia state code. [Additional detail and specific references to code can be added here if helpful.]
Financial:
The additional focus on infill housing within the comprehensive plan may require extra work beyond what may have been already budgeted for the project. Furthermore, the legal process necessary to take or transfer ownership of blighted properties can generate substantial court and attorney fees.
Organizational: 
Current city staff and resources (along with any planned consultant assistance) are likely fully prepared to successfully complete the comprehensive plan update. However, the additional programmatic and property-related analysis described in this solution may not be within that capacity. Similarly, a fully new interactive web application to reveal and promote infill development opportunities may be beyond staff availability and capability.

FUNDING SCOPE REQUIREMENTS AND PROJECTED IMPACT

Total new funding required to complete the tasks described in this solution depends on how significantly parts of that work are incorporated into staff activities already projected in the comprehensive plan budget and scope.
Contract cost for an outside consultant to complete the analytical work in Task 1 would likely fall around \$5,000, depending on scope. Contract cost for work described in Task 2, including a standalone interactive web application, could range from \$10,000 to $20,000. These are very rough estimates and should only be used to initiate further discussions prior to any RFP being drafted.

POTENTIAL FUNDING SOURCES

Virginia Housing’s Community Impact Grant is purpose-built for many of the tasks included in this solution. Applications are accepted on a rolling basis. Awards range from \$15,000 to \$20,000 depending on project type.
CDBG funds may be used for planning and capacity building activities. Allocation of any CDBG funds for this work should be planned and structured to achieve specific objectives and activities described in the City of Lynchburg 2020-2024 Five Year Consolidated Plan.
City general funds and private philanthropic grants may also be explored as funding options.

METRICS TO EVALUATE SUCCESS

Number of vacant/blighted/delinquent parcels transferred and remediated
Number of new infill homes created
Number of new homeowners and/or renters occupying those homes
Total and average property value increase (and subsequent tax revenue)
Number of citizens and stakeholders engaged on this topic within comprehensive plan process
Relevant HUD paper on infill
Preserve the existing affordable housing rental inventory
Issue: Large segments of subsidized housing are aging out of their affordability commitments

Low-Income Housing Tax Credit (LIHTC) properties have a 30 year commitment to affordability, but only a 15 year compliance period, wherein property owners can increase rents. Nonprofit developers will often seek new allocation of tax credits before their commitment period ends, but there is often little incentive for for-profit developers to maintain affordability restrictions past the compliance period. By 2035, over 40 percent of active LIHTC units in Lynchburg are set to exit their affordability commitment period.

### Develop an Affordable Housing Preservation Fund

FRAMEWORK

Solutions dedicated to preserving existing affordable housing and LIHTC properties include obtaining additional allocation of tax credits, providing financial incentives to property owners and developers, and investing in maintenance and repairs to extend the lifespan of this segment of the housing stock.

While housing trust funds are often used to preserve and rehabilitate affordable housing units, they typically prioritize new construction and aid with predevelopment and gap financing. Instead, local preservation funds have been developed to ensure that the gains in newly constructed affordable housing are not negated by the conversion of affordable units to market rate.

Examples of such financing programs exist in Virginia, specifically in Loudoun County, which has been facing severe housing market pressures. Fairfax County also assembled an Affordable Housing Preservation Task Force in 2020 to provide the Board of Supervisors with policy recommendations to support the preservation of affordable housing.  
Affordable housing preservation funds are no different than housing trust funds in terms of their structure and administration. These are layered sources of funding involving public sector and sometimes private sector or philanthropic funds to capitalize a revolving loan fund. 

IMPLEMENTATION

Immediate:

Assemble a comprehensive list of LIHTC properties in the City of Lynchburg, with a focus on the physical conditions of the building, subsidy expiration, number of affordable units, and ownership structure (i.e. nonprofit, for profit, etc.).
Determine the total number of units at-risk of conversion in the next five years; make comparisons to what is currently in the development pipeline.
Conduct outreach to LIHTC property owners to determine their intended plans after commitment period expiration and assess funding needed to maintain affordability.
Educate elected city officials about the importance of an affordable housing preservation fund and how it will prevent net loss of affordable rental units in the city. Use the list of LIHTC properties and anticipated loss to help support education efforts.

Short-term:

Determine the level of support that is achievable from elected officials.
Identify additional sources of capital—including participation from lending institutions, corporations, and charitable foundations.
Develop a detailed implementation model that incorporates the new sources of capital that the preservation fund will administer. Application review, scoring and selection procedures must be developed and approved by City Council.

Mid-term (12-24 months):

Explore the potential for “dedicated” sources of revenue to the fund. Dedicated sources allow for greater predictability in the volume of resources and remove any fiscal cycles and shifting political priorities from affecting the operation.

Long-term (24+ months):

Monitor and evaluate the fund’s performance by determining the total number of units preserved by the fund.
Gather data on demographics of residents and other information to measure greater community impacts.

LEGAL, FINANCIAL, AND ORGANIZATIONAL CAPACITY

City staff should conduct an assessment of new legal and financial liabilities that accrue from the administration of funds from new sources—including local governments, banks, corporations, and charitable institutions. When funds are provided to the fund from any of these sources in the form of grants, the fund should have a standard set of requirements that are included in the grant agreement, including clarity around liability, lending, and grant making procedures, procedures and reporting.
City staff should evaluate staff capacity to add new products and procedures.  If private funding requires traditional bank style “underwriting” then there may be a need for training or the outsourcing of certain elements of the loan / grant origination process.
Similarly, if loan servicing, including collection and application of payments, is part of an expanded fund, that will also involve software and accounting upgrades as well as staff training. These functions could also be outsourced to a lending institution or to Virginia Community Capital—Virginia’s statewide CDFI.   

FUNDING SCOPE REQUIREMENTS AND PROJECTED IMPACT

Given the scale of housing needs in the City of Lynchburg, we recommend that the goal for preservation fund capitalization be at least $1 million per year. Most housing trust funds in the state are capitalized at levels that meet or exceed this amount.
Based upon anticipated funding levels, the fund should set preservation goals for a 3-5-year period. Because of the often lengthy periods of time to close on acquisitions or obtain gap financing, these projects will frequently carry over from one year to the next. 

POTENTIAL FUNDING SOURCES

General fund appropriation: The most common source of funding for local housing trust funds is a general fund appropriation from the locality.  While the “gold standard” for affordable housing funds  is a “dedicated” revenue source from a fee or tax, that approach is not the standard across Virginia. Currently, most trust funds in Virginia are funded with combinations of local general fund appropriations and federal housing funds, with some localities also incorporating dedicated revenue sources as a partial income stream.
Private and philanthropic sources: A wide range of nonpublic funding sources have supported affordable housing funds around the state and the country. These include banks and other financial institutions that provide loan and grant funds.  Corporations, philanthropic foundations, and other community anchor institutions, including hospital systems, colleges and universities, and churches can be substantial partners.
With regard to the mix of grants and loans, any affordable housing fund that can secure a greater level of grant funding compared to loans will have greater flexibility in terms of the needs that it serves as well as its attractiveness to the affordable housing development community. Loan funds may be available from a wide range of actors—for example, Virginia Housing and Virginia Community Capital both provide loan funds on favorable terms for affordable housing developments.
We recommend not bypassing local lenders in favor of working strictly with state sources. Local lenders will frequently be able to tailor their lending specifically to local needs and align with other affordable housing fund resources. State sources will be especially useful as a significant element of the capital stack needed to develop affordable projects in the region, but they will conform to a statewide standard. 

METRICS TO EVALUATE SUCCESS

A critical element for a successful affordable housing fund is to be able to measure both outputs and outcomes. 
Outputs: It is important to collect data on the number of housing units preserved, their location, cost and other relevant data points. While these metrics may not materialize until the second or third year after the first allocations, such data is necessary.
Outcomes: It is just as, if not more, important to measure who is being helped and assess whether objectives are accomplished. This information is more difficult and time-consuming to collect but is crucial to sustaining funder commitment in the long run.

RESPONSIBLE ACTORS AND THEIR ROLES

The key actors in this process will be the housing staff (or assigned staff) from the City of Lynchburg who would be responsible for developing this program proposal and assessing viable funding sources, programmatic design, administration, etc.
RELEVANT EXAMPLES

The Loudoun County Rental Housing Acquisition and Preservation Loan Program was created in early 2022. The program acts as a gap lender to help finance the acquisition and preservation of existing multifamily rental developments in the County.

The program is administered by the Loudoun County Department of Housing and Community Development. Requirements placed on the funding include a set percentage of units designated as affordable (20% of total units affordable at 50% Area Median Income (AMI) or 40% of total units affordable at 60% AMI. In addition, the County places a 30-year affordability commitment on properties utilizing the fund.

The source of funds for the initial capitalization of the RHAP fund was the FY 2021 Fund Balance from Loudoun’s existing Housing Fund, \$5 million. Staff has since recommended that a portion of the FY 2023 real property tax rate be dedicated to the RHAP program, approximately \$6.5 million. 

For more information, visit Loudoun County Rental Housing Acquisition & Preservation Loan Program.

## Secondary Solutions 

### Continue the work of Lynchburg Housing Collaborative 

Issue: Through the work of the regional housing collaborative, Lynchburg municipal staff and housing organizations have provided city council policy ideas to create more home ownership and affordable rentals opportunities and address the need for more affordable housing throughout the entire city. To date, some recommendations are yet undeveloped or still being explored.

The Lynchburg Regional Housing Collaborative was established with the support of the city council to: 1. Create a detailed analysis of the current housing market, 2. assess the challenges faced by lower and middle-income households, and 3. examining the potential efficacy and impact of the proposed policies. Following their 2019 report to council, some priorities and policies remain undeveloped and are an avenue for continued policy growth.  

Solution: Pursue recommendations made through the collaborative that address the priority of increasing housing opportunity for all income levels, and further build the collaborative through targeted recruitment to include representatives from lending institutions, private residential developers and other anchor institutions.

FRAMEWORK

Housing shortages and the lack of affordable options present significant obstacles to community development and stability. Inclusive and diverse communities are advantageous not just for the individuals who benefit, but for the community as a whole. Communities that strive to include a wide range of household types have been shown to foster entrepreneurship, community-based economic activity, and educational improvement. Adopting inclusionary housing practices and diversifying the regional housing collaborative’s membership to increase stakeholder engagement are primary strategies to build from existing policy groundwork. 

Under Section § 15.2-2305.1 in Virginia law, Lynchburg can create inclusionary zoning programs that provide density bonuses and other incentives in exchange for a developer voluntarily electing to provide affordable housing. Lynchburg currently has no legal authority to mandate affordable units in new construction. 

IMPLEMENTATION PLAN 

Immediate (0-6 months):

Review § 15.2-2305.1 and the provisions included in the code owing to HB1101 from the 2020 General Assembly session, which provides applicable localities with much more prescriptive guidance.
Use digital mapping programs to spatially analyze AMIs across the city and where housing needs are distributed. Choose a price and AMI range to target using an ordinance.
Plan for how inclusionary housing policies could be tied to other priorities like transportation
Engage anchor health and education institutions to join the housing collaborative

Short-term (6-12 months):

Conduct outreach to housing officials from Fairfax County, Loudoun County, and the City of Alexandria. These localities have longstanding inclusionary zoning ordinances created under §15.2-2304. Seek guidance on the following:
Administration needs and capacity.
Best practices for outreach to developers and builders.
Data tracking and reporting.
Methods to build-in programmatic flexibility and resiliency.
Make the case for addressing affordable housing needs and illustrate how an inclusionary housing program would begin to solve the problem. Outreach efforts should address common questions like: 
What is inclusionary housing?
Why do we need inclusionary housing?
Why is inclusionary housing useful?

Long-term (12-24 months):

Draft a full ordinance and gather feedback from stakeholders in formal and informal settings.
Assess the ordinance’s potential impact on developable land in the town. Learn the opinions and projections of builders and developers
Consider pursuing legislative action in the General Assembly to join the six localities authorized to adopt inclusionary zoning ordinances, or “affordable dwelling unit” (ADU) ordinances under VA § 15.2-2304.

RESPONSIBLE ACTORS AND ROLES

Local planning staff will help draft and design the ordinance.
Planning commission and town council will review drafts, provide feedback, and adopt the final version.
Developers and builders will provide meaningful input and conduct provisions in the ordinance to add affordable units to new construction.

POTENTIAL FUNDING SOURCES

No specific sources required.

RELEVANT EXAMPLES 

Montgomery County, Maryland 

Approach: Montgomery County operates one of the most established inclusionary zoning policies in the nation. Their Moderately Priced Dwelling Unit (MPDU) program mandates that 12-15% of units in new residential developments are reserved for affordable housing.

Outcomes: Since it was established in the 70s, over 11,000 affordable units have been created in the county through the MPDU program and through developer incentives including a waiver of water, sewer charge and impact fees. 
