# Appomattox County

## Primary solutions

### Provide support for the aging population

**Issue:** *A growing number of seniors in the county require homes and services to support their mobility status and changing health needs.*

An increasing number of older adults are choosing to "age in place" (AIP) and stay in their own homes and communities for as long as possible. Across the region, the senior population grew by 9,021 individuals from 2012 to 2021. Appomattox, in particular, saw an 81 percent increase in renters aged 45 to 64 years old between 2010 and 2021.

**Solution:** *Adopt and implement an AIP framework for local builders to address essential home modifications and community adaptations that address residents and life-stage changes.* 

Solutions include finding and/or training regional developers capable of retrofitting existing homes and building new patio-style housing that address accessibility needs. This work must be intentionally built into development patterns and transportation infrastructure to ensure seniors can access health and services needed outside the home, particularly in rural areas or areas along county lines. 

**FRAMEWORK**

While aging in place has always been the first choice of seniors, baby boomers are choosing this approach to aging at a rate well beyond their parents. Existing research shows that more than two-thirds of boomers want to stay in their homes as long as possible and resist the idea of moving into retirement homes, even as children and families are increasingly moving away from their parents.

Beyond the social motivations for this shift, the financial benefits of aging in place have also influenced many to seek this path. According to the Genworth Cost of Care Survey 2021, the average cost of assisted living in the Lynchburg region is \$4,625 a month.

Housing modifications become increasingly important as people age in order to assist in their adaptation to changing capacity and to maintain a sense of well-being and independence in daily life. The relationship between housing and health is especially important in very old age as older adults are more vulnerable to environmental challenges.

Designing an Aging in Place program involves at least two essential categories: Home modification and community adaptation.

**Home modification** begins with an assessment by a qualified professional.

* Often these are people with an occupational therapy background.
* They walk through the home with the resident to determine their individual physical needs and how the home needs to be modified in order to accommodate those needs.
* The home assessment will look at current and future needs so that the plan can be put in place to ensure that the house will continue to need the changing needs of the residents.
* Once the modification plan is in place, the challenge is to find a qualified contractor who will be able to accomplish those modifications at a cost the homeowners can afford.
* Since many seniors have limited incomes, it is important to be able to find sources of subsidy that can make it possible for seniors with limited incomes to be able to take advantage of all modifications that will keep them safe.

**Community adaptations** relate to changes in public spaces that can facilitate an ease of access to community and services.

* As seniors drive less, for example, there is a need to find transportation services that can take the place of self-driving.
* Many communities are also looking at changing their own development patterns and infrastructure to make it easier for seniors to age in place in a way that does not separate them from the community. 

**IMPLEMENTATION PLAN**

*Immediate (within 6 months):*

* Evaluate existing networks and leadership: Identify service providers and community leaders who are currently involved in working with seniors and would be well positioned to join a countywide Aging in Place Leadership (AIP) Team. This team would be responsible for organizing and guiding a comprehensive initiative following successful models like those in the New River Valley and the Village network model in Northern Virginia.
* Identify gaps: Learn where the gaps exist in housing needs and services for seniors (i.e. access to food, transportation, recreation, etc.).
* Map areas of concentration: Map the location of senior households in the area using tract or block-group level American Community Survey estimates to understand where concentrations exist.
* Evaluate survey data: Review prior surveys of senior renters and homeowners in the region to refresh the understanding of their preferences and plans with respect to housing. Update findings as needed.
* Seek best practices for an AIP policy: Research best practices from similar communities as to how they built AIP into policy and program decisions at the local level---for example, as a part of new developments or streetscapes.

*Short-term (within 12 months):*

* Establish timeline and resources: Assembly a county-wide AIP Leadership Team to meet on an established basis. Develop an action plan by placing the AIP initiatives on a timeline and identify the resources needed for implementation. If resources do not permit full scale implementation, identify initiatives that can be piloted by order of priority.
* Develop a home-modification program: Implement a comprehensive home-modification initiative that incorporates the following elements:
  + Home assessments: pursue outreach to older residents to support home self-assessments as well as access to low-cost certified home assessments.
  + Quality construction: coordinate with qualified contractors and use a construction quality control process.
  + Financial assistance: provide financial assistance to homeowners on terms that are consistent with their ability to pay for AIP home modifications.
  + Program navigation support: Many seniors will need a navigator/coordinator to help them through the process.

*Long-term (within 24 months):*

* Coalition build beyond the county: Support localities in mapping and prioritizing the needs of their residents and identify areas of shared priority to be pursued at either a regional or local scale (perhaps as a pilot project if funding is limited). Ensure the CoC, regional healthcare providers, and other partners understand and are on board with plans.
* Strengthen capacity: Establish consistent funding sources and training programs to continue to provide a stream of home modifications services to address all levels of need. This may involve create hub locations in rural parts of the county.
* Incorporate AIP in housing education and outreach: Make AIP part of follow-up housing study conversations and outreach. If a housing forum is held, make AIP one track within the event.
Use the existing community/senior centers, community events, and/or hospitals as natural venues for disseminating relevant information.

**RESPONSIBLE ACTORS AND THEIR ROLES**

* AIP leadership team: Initiate and coordinate program activities.
* Local government staff: Educate partners and clients on information for existing resources, and assist with implementation.
* Local senior service agencies, housing and healthcare providers, counselors, and volunteers: Provide direct services and update leadership team on changing needs and opportunities.

Connecting with regional institutions and leadership can further strengthen the work of local actors.

**LEGAL, FINANCIAL, AND ORGANIZATIONAL CAPACITY**

* As with any program where advice is being given and changes are made to the homes of seniors, it is important to carefully assess legal liability. Making sure that providers are professionally trained and certified and that contractors are properly insured are critical elements to a properly designed program.
* Aging in place is an extensive undertaking. It will require coordination of many agencies and organizations. The AIP leadership team is the starting point for this and can be built out with other public and private sector leaders.

::: callout-note

### Longevity Project

*Richmond, Virginia*

One model is to create a coordinating council that provides guidance and measures impact. In the Richmond area, that organization is the Longevity Project---a coalition led by VCU's Gerontology Department but that includes local governments in the region as well as many housing and service providers.

[The Longevity Project for a greater Richmond](https://gerontology.chp.vcu.edu/about-us/longevity-project-for-a-greater-richmond/)

:::

**FUNDING SCOPE REQUIREMENTS**

Because of the size of the senior population and its continuing projected growth, the funding requirements of a full-scale aging in place program may be very substantial and need to include the following components:

* Home assessment costs
* Renovation and retrofitting costs
* Builder training and certification
* Financial assistance programs
* Outreach and education
* Program administration
* Monitoring and evaluation

**POTENTIAL FUNDING SOURCES**

Many traditional affordable housing funding sources can also be accessed to assist lower income seniors with aging in place. Most of these programs are means tested and only available to seniors with incomes below 80% of AMI and in many cases, less than 50% AMI.
These include:

* State and federal grant programs: Funding programs through the DHCD, HUD, the United States Department of Agriculture (USDA), and Virginia Housing exist that may serve the housing needs of seniors; however, these sources have significant limiting factors to serving effectively for home modification needs. CDBG funds, distributed by DHCD, may be used for a wider variety of housing, community and economic development activities. These funds could be used to make home modifications or repairs as well as make community adaptations.
* Medicaid and Medicare: The Commonwealth Coordinated Care Plus (CCC Plus) is a Medicaid managed long-term services and support program that includes some minor home modification services for qualifying seniors. Medicare and Medicaid reimbursement rules are also providing strong incentives for health care institutions to address the housing status of their patients.
This could include partnering for home modification initiatives---especially those in which trained occupational therapy professionals can evaluate home conditions and make recommendations.
* Nonprofit assistance: Local affordable housing providers like Habitat for Humanity have demonstrated experience providing home modifications. The Southeast Rural Community Assistance Project, (SERCAP) Aging in Place program, based in Roanoke, provides support services to help individuals who wish to continue living at home despite health setbacks, including adaptive design solutions for homeowners.

Aging in place, however, is not a unique need for lower income seniors. Many seniors with significant retirement income as well as substantial home equity are also in need of AIP assistance.

Any AIP program in the region/the AIP leadership team should recognize this and make access to programs and services available on a market rate basis, and connect local developers with the tools to succeed in providing the best fit for buyers.

**METRICS TO EVALUATE SUCCESS**

* Lengthened tenure for seniors aging-in-place (i.e., residents are able to stay in their homes as long as they had planned)
* Improvement in health conditions:
  + Decrease in the number of injuries incurred in the home
  + Increase in life expectancy
  + Better mental health outcomes (e.g., lower rates of depression and loneliness)
* Fewer emergency room visits and lower long-term healthcare costs

**PROJECTED IMPACT**

The potential production and impact of these programs could be quite large. Most aging in place programs balance costs by starting very modestly with specific targeting of households and certain types of housing modifications. The program can expand from there depending on resources, both financial and human.

**BEST PRACTICES AND EXAMPLES**

::: callout-note

### Albemarle Housing Improvement Program (AHIP) - Seniors Safe at Home

**Approach:**

The Albemarle Housing Improvement Program (AHIP) is a 30-year-old housing organization located in Albemarle County, Virginia. Over the last decade, AHIP has evolved into an agency that primarily serves seniors with a range of services to help them stay in their homes longer.

Seniors Safe at Home sets out to make sure that no senior citizen must wait for a critical home repair while helping them preserve assets and age in place. The types of repairs vary and include heating/cooling, roof leaks, stair and porch repair, kitchen and bath accessibility, plumbing and electrical problems, and issues with well and septic systems.

**Outcomes:**

In 2016, this program helped 98 senior citizens with repairs and rehabs, or 53% of AHIP's clients---as of 2021, the number of seniors rose to 66% of their total rehab participants.

AHIP uses a variety of funding sources; however, the largest share of its support comes from the City of Charlottesville and Albemarle County. Both of these jurisdictions use local and HUD funds to support AHIP's work. AHIP also raises a substantial amount of charitable funding every year from corporate and philanthropic sources as well as individuals.

[AHIP - Safe at Home](https://ahipva.org/programs/safe-at-home/)

:::

::: callout-note

### The Village Movement

**Approach:**

The Village Movement began in the United States nearly 20 years ago. The program is based on the idea of volunteerism. Seniors in the community join and form a nonprofit organization with a modest annual fee, and most organizations hire a coordinator who helps the members find services such as in-home care, handyman help, drivers, and meal delivery.

Frequently, other members of the community will volunteer to help individuals who are a part of the village. For example, a young person in the neighborhood might be willing to mow a lawn, rake leaves, clean gutters, take out the trash, or change a ceiling light bulb for a senior resident.

**Outcomes:**

There are now more than 220 Village programs across the country and at least 10 operating in Virginia (primarily in Northern Virginia).

[The Village Movement](https://www.helpfulvillage.com/the-village-movement)

:::

::: callout-note

### College Service Project: Appalachia Service Project Services for Homeowners

**Approach:**

The College Service Project (CSP) is a student-led campus-based organization that affiliates each of its chapters with the Appalachia Service Project (ASP). The CSP follows the ASP model for home repair projects in their local communities. College students and other volunteers make critical repairs on homes and build new homes when current dwellings are beyond repair.

More than 15,000 volunteers give their time to repair and build homes with the Appalachia Service Project. This model could be replicated with the universities and colleges located in the Lynchburg region.

**Outcomes:**

In the fifty two years since the Appalachia Service Project's founding in 1969, over 400,000 volunteers have repaired nearly 20,000 homes. Not only does the service create safer living situations for rural families in Appalachia, it also establishes meaningful relationships between repair staff and homeowners. Likewise, youth and adult volunteers gain experience and confidence to make important home repairs.

[ASP Services for Homeowners](https://asphome.org/homeowners/)

::: 

### Attract and incentivize developers to build lower-cost homes and increase housing diversity 

**Issue:** *A shortage of building construction and specialty trade contractors across the region is a major constraint on construction of new housing, and there is a lack of variety to meet residents' lifestyles and budgets.*

The region faces greater demand for housing than can be supplied by the current array of developers, particularly dedicated affordable housing produced by nonprofits and other mission-driven organizations. One-person homeowners households are increasing in Appomattox, indicating changes in family structures in the county.

**Solution:** *Invest in and support the growth of affordable developers and builders, and reevaluate development regulations to allow for greater density and diversity of housing.*

Attracting and incentivizing developers who can deliver lower-cost options requires a combination of financial, regulatory, and technical support. Furthermore, increasing housing choice diversity is important for promoting equitable and inclusive communities, reducing segregation and discrimination, and providing a range of housing options for people with different incomes, backgrounds, and lifestyles.

**FRAMEWORK**

A combination of efforts are required to address the issue of affordable housing supply-chain.
Appomattox County can explore ways to align development regulations with their desire to address housing that is more accessible and affordable to young families, seniors, and modest-income households. This can include streamlining the development process, offering zoning and land use incentives, providing financial support, and increasing technical programs and assistance to navigate the unique requirements of affordable housing.

Through strategic implementation of these tactics, it is possible to create an environment that is attractive and conducive for developers to contribute meaningfully to housing diversity and affordability, and to minimize obstacles preventing affordable housing development.

**IMPLEMENTATION PLAN**

*Immediate (within 6 months):*

* Establish a task force comprising housing experts, developers, local government representatives, and community stakeholders. This body will analyze current housing policies, evaluate existing regulation and identify barriers, and determine what incentives would most effectively attract developers.
* Initiate open dialogues with potential private developer partners to better understand their hesitations and needs concerning affordable housing projects. This information will guide the task force in designing appealing incentive packages.
* Develop a blueprint for a technical assistance program, which will offer guidance on navigating regulatory hurdles and securing funding for affordable housing projects.

*Short-term (within 12 months):*

* Roll out chosen financial incentives, which could include a combination of property tax abatements, density bonuses, low-interest loans, or grants to developers undertaking affordable housing projects depending on identified need and impact.
* Execute regulatory reforms, including a streamlined development approval process, relaxation of zoning laws to accommodate diverse housing types, and a fast-tracked review process for affordable housing proposals.
* Launch the technical assistance program, offering training sessions and resources to assist developers in understanding and overcoming the complexities of affordable housing development.

*Long-term (within 24 months):*

* Develop public-private partnership frameworks and attract new private entities to participate in affordable housing projects.
* Continually monitor the effectiveness of all implemented measures, modifying strategies as necessary based on outcomes and feedback.

**RESPONSIBLE ACTORS AND THEIR ROLES**

Public entities, private developers, and non-profit organizations will all have roles.

* Public entities will provide policy guidance and be responsible for executing any chosen regulatory reforms.
* Private developers will bring in the required building expertise, efficiency, and scalability.
* Non-profit organizations can assist in community engagement, offering local knowledge and fostering support for affordable housing projects.

**LEGAL, FINANCIAL, AND ORGANIZATIONAL CAPACITY**

* Training programs should cover how local zoning regulations could influence the planning and execution of affordable housing projects, including the potential need to navigate variances or amendments to these regulations. Training must also include understanding the Virginia Residential Landlord and Tenant Act and its implications on managing affordable housing units.
* Developers should be educated about Virginia's Low-Income Housing Tax Credits (LIHTC) and how to leverage this program to finance affordable housing development.
* Building organizational capacity involves training developers on project management, collaboration with local organizations and government entities, and compliance with affordable housing regulations.

**FUNDING SCOPE REQUIREMENTS**

Funding requirements will depend on the scale of the implementation. Initial costs will be associated with establishing the task force, designing incentive packages, and setting up the technical assistance program. Long-term operational costs will include maintaining partnerships, managing programs, and funding financial incentives.

**POTENTIAL FUNDING SOURCES**

1. Government funding:
  + Federal grants, such as the HOME Investment Partnerships Program or the Community Development Block Grant (CDBG) program.
  + HUD's Thriving Communities Technical Assistance (TCTA) Program helps localities to address their housing needs, including addressing regulatory and procedural reforms.
  + Targeted grants for housing planning efforts are available from DHCD and the Appalachian Regional Commission.
  + The Capacity Building and Community Impact Grant programs from Virginia Housing could help fund technical assistance efforts and development planning.
  + The Virginia Housing Trust Fund (VHTF) provides loans with low-interest rates for affordable housing projects.
2. Public-Private Partnerships (PPP):
  + Private sector entities often participate in affordable housing development through PPP arrangements.
  + The private sector brings in capital and operational efficiency, while the public sector can offer incentives like tax breaks, land, or eased regulatory requirements.
  + Low-Income Housing Tax Credits (LIHTC) can be one example of this type of partnership.
3. Philanthropic Resources:
  + Local/regional foundations, businesses, and professional associations could potentially sponsor events and other activities.

**METRICS TO EVALUATE SUCCESS**

* Number of affordable housing units developed
* Uptake of financial incentives by developers
* Efficiency of the regulatory approval process
* Increase in housing types
* Number of new affordable developers in the county

**PROJECTED IMPACT**

With a well-executed plan, this approach could substantially increase affordable housing availability and diversity within the region over the next few years, with impacts on individual, community, and economic levels.

::: callout-note

### City of Arlington - Affordable Housing Investment Fund (AHIF)

**Approach:**

The city of Arlington has expanded affordable housing by providing low-interest loans to developers through AHIF, introduced bonus density provisions, and actively involved communities in decision-making processes.

**Outcomes:**

The program has enabled the majority of the approximately 8,300 rental units approved throughout the County that help provide homes for low- and moderate-income households, including specialized housing for the elderly, the homeless, or persons.

[Affordable Housing Investment Fund](https://www.arlingtonva.us/Government/Programs/Housing/Development/Affordable-Housing-Investment-Fund)

:::

::: callout-note

### Austin, Texas - Small Developer Training

The Small Developer Training program launched in 2023 and aims to boost the availability of affordable housing in Austin by equipping small-scale developers skills and knowledge necessary for successful residential development.

[Austin Small Developer Training](https://housingworksaustin.org/education/austin-small-developer-training/)

:::